### ISSUE TITLE
Better maintenance page

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#103]
We shouldn't hopefully ever have to enter maintenance mode again, but if we do, we should have something way better than this. It should explain what's happening and how long it will take.
![2016-10-04-002202_1464x456_scrot](https://cloud.githubusercontent.com/assets/538235/19056310/b03a29ac-89c8-11e6-9968-ff11040a795d.png)

**Comment by Cantido** [comment]
This is another one that will benefit from having S3 set up, since we can tell Heroku to render an arbitrary URL for us, and they recommend something on S3.

**Comment by drusepth** [comment]
Will still need to set up S3 for #52, but this was fixed with https://github.com/indentlabs/notebook/pull/180 so I'll close. :+1: 

Maintenance page is hosted at http://notebook-static.herokuapp.com/503
