### ISSUE TITLE
Reduce memory footprint

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#105]
Heroku gave us a little guidance:

![There have been 1274 memory errors in the current time period.](https://cloud.githubusercontent.com/assets/1505603/19057308/82115750-8994-11e6-90b2-0b90ee8158b8.png)

That link leads to [this article on Ruby memory usage](https://devcenter.heroku.com/articles/ruby-memory-use).

**Comment by Throne3d** [comment]
One of my apps reduced in memory usage quite a lot when we upgraded from `aws-sdk` version 2 to the individual subcomponents that version 3 uses. This app looks to be on `1.5`, so it might not help here, and it might also not be a straightforward upgrade, but that could be a way to decrease memory usage? Gems can be quite heavy.

**Comment by drusepth** [comment]
We haven't had any memory issues in quite some time now, so I'm gonna close this to clean up issues a bit more.
