### ISSUE TITLE
Prepaying for Premium doesn't adjust upload storage bandwidth

### ISSUE THREAD

**Issue by mbround18** [indentlabs/notebook#1099]
### Expected behavior

- Prepaid for 3 months to test the software and expected 10gb of file storage. 

### Actual behavior

- I only have 50mb of file storage. 

### Steps to reproduce the behavior

- prepay for a subscription.

**Comment by drusepth** [comment]
It looks like this is indeed a bug that needs fixed. Thanks for the heads up!

I'll try to get this fixed soon. In the meantime, feel free to PM me (@andrew on the site) and I can manually adjust your storage.

**Comment by mbround18** [comment]
Just following up, still an issue

**Comment by drusepth** [comment]
@mbround18 Thanks for following up; this got lost in the shuffle a bit. Can you send an email to andrew@indentlabs.com with your account's email? Or, feel free to post a link to your profile here. However you want to get it to me works for me! I'll also extend the code you purchased another month to apologize for the delay and thank you for pointing this out. I appreciate it!

**Comment by drusepth** [comment]
This should be fixed for all prepaid upgrades going forward. I'll also be running a script today to ensure everyone's current bandwidth is correct for their current billing plan which should fix it for all existing upgrades as well. Sorry for the inconvenience here, but this should resolve the issue!
