### ISSUE TITLE
Content Edit forms not using ActiveRecord translations

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#110]
Saw this field today, labeled "Identmarks," even though we have provided the correct name "identifying marks" in `en.yml`. We need to review the content forms and make sure we are using `Model.human_attribute_name(attribute)` for all attributes, so that the proper name shows up.

At the moment, we don't have all of the fields localized, but that's easy peasy to include along with this fix.

![image](https://cloud.githubusercontent.com/assets/1505603/19098926/041348ca-8a77-11e6-8c60-b5cfd1746a59.png)

**Comment by drusepth** [comment]
I think this is fixed in the new views, right?

**Comment by Cantido** [comment]
Yep!
