### ISSUE TITLE
Users should be able to toggle on/off content type per-universe to use in that universe

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#113]
As the title says. When a user creates a universe, we should have some toggles for them to enable/disable characters, locations, items, races, worlds, etc for that universe. 

This means the following changes to the UI, also:
- The content links in the top-right should now be the set of all content types enabled across all of a user's universes
- If a user is scoped to a particular universe (from the top-left dropdown), the top-right content types should just be the content types of that universe
- The quick-add FAB in the bottom-right should always contain all content types enabled across all of a user's universes
- Universes should always be included as a content type in both of the above lists
- Characters, Locations, and Items (the basic content types) should also always be included in both of the above lists, unless specifically disabled in a universe we're scoped to

We probably want to make a "Containers" tab on Universe to accomplish this. I think either a list of material design toggles or a grid of enabled/disabled content types with icons would work. 

We pretty much need this before starting to implement any of the extended content types to prevent overwhelming users with content types they don't want or care about.

**Comment by babelfish** [comment]
A list of toggles could get overwhelming as more and more content types are added.

What do you think of adding a "hide" button on the index page for each content type which disables that content type, along with making a list of currently disabled types available for re-enabling?

**Comment by drusepth** [comment]
@babelfish I think that'd be a smoother solution, though I wonder how it'd work with people who might, for example, want to plan creatures in only one universe. When they're working in that universe, would they need to go unhide Creatures, and then hide it again whenever they flip back to any other universe? That feels inconvenient to have to do, but maybe I'm wrong.

**Comment by drusepth** [comment]
This is done and live.
