### ISSUE TITLE
Basic text formatting

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#114]
Users should be able to use some basic text formatting (markdown, bbcode, dunno) in fields and have it displayed properly on content pages. Things like bold, italics, underline, and linking to other notebook pages (a la [[Chad]]) would be great.

**Comment by mpigsley** [comment]
My vote here is for markdown 🎉 
I find myself creating lists rather than large blocks of paragraphed text.

**Comment by drusepth** [comment]
https://github.com/indentlabs/notebook/pull/124 implements markdown on all fields (and adds spaces between paragraphs). No content-specific [[linking]] yet, but I think we'll add that after markdown is merged.

**Comment by drusepth** [comment]
Markdown is live. We'll revisit a shorthand for linking to other notebook pages in a new issue.
