### ISSUE TITLE
Keyboard controls

### ISSUE THREAD

**Issue by andrewcarreiro** [indentlabs/notebook#121]
Would you accept a PR for the following keyboard controls?

- **n+c** jump to create new character form
- **n+u** jump to create new universe form
- **n+l** jump to create new location form
- **n+i** jump to create new item form
- **CMD+>** Switch to next tab in a form
- **CMD+<** Switch to previous tab in a form

**Comment by drusepth** [comment]
Of course!

Two questions:
1. Would CMD+>/< map to Ctrl+>/< on PCs? (Is that what CMD normally maps to?)
2. What do you think about swapping **n** with (capital) **N** in the other mappings? I think it'd minimize accidental navigations to other pages when someone types without realizing a field isn't focused (or defocuses). Might be easier than implementing a "you have unsaved changes" JS popup before navigating.

I've always wanted some keyboard shortcuts. They'd be awesome for power users. The only other one I'd recommend is **?** with a Gmail-esque popup explaining the available shortcuts.

**Comment by andrewcarreiro** [comment]
1. Yep, I think so. Assuming that doesn't conflict with anything?
2. Makes sense!
3. I'll see what I can do about a tutorial pop-up.

Thanks! :)

**Comment by andrewcarreiro** [comment]
Also: what browsers are being targeted? Can I get away with some ES6 instead of writing coffeescript?

**Comment by drusepth** [comment]
1. Assuming that doesn't conflict with anything, of course (I don't think it does). Feel free to throw a different mapping at it if so.

Also, here's our browser breakdown:
![2016-10-10-235629_408x532_scrot](https://cloud.githubusercontent.com/assets/538235/19252611/f85d4700-8f45-11e6-958c-2988fc2ca0f5.png)

I think with a nonessential feature for powerusers, it's okay to not support every browser. If we could just support like the latest two versions at least in Chrome/Firefox (and IE/Edge if possible), that'd be awesome. 

We don't really have a spec for what browsers we support in the main site, but I typically just do all my testing in Chrome/Firefox.

**Comment by drusepth** [comment]
This is live and working well. Tweeted it out, and hopefully we'll get some feedback for future iterations! :) Thanks for the implementation!
