### ISSUE TITLE
Select Dropdown Styling

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#123]
It looks like the materialize padding isn't applied to the dropdowns and the font size of the labels are slightly large than the rest.

<img width="990" alt="screen shot 2016-10-11 at 7 15 14 am" src="https://cloud.githubusercontent.com/assets/3017491/19269919/d0d79f72-8f82-11e6-8ebb-1dbbcf0c6287.png">

**Comment by mpigsley** [comment]
As a side note. Do you all prefer I submit the problem via the google form from the website or here as an issue?

**Comment by drusepth** [comment]
@mpigsley Here is good, the good form is more for a catch-all for everyone without a github account. :)

Also, just saw your message on reddit as well. To submit your fix you should be able to fork this repo, make the change, and submit a pull request back in. I think that's the standard path for submitting pull requests to organizations without the org giving everyone access to push. Let me know if you've got any questions on it. :)

**Comment by drusepth** [comment]
@mpigsley Thanks for this!
