### ISSUE TITLE
Admin Privacy

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#136]
Just realized I could get to the admin page on production. Is that something that should be limited to a certain set of admins? Especially if there are plans to expand that space.

**Comment by Cantido** [comment]
Definitely worth doing at some point, though I think it's kinda nice to show how the site is doing. At the moment, none of that data is personalized, so at least there is no security issue.

**Comment by mpigsley** [comment]
Yup! It's neat that the graphs are public for sure. Just wondered if that was the intended effect and what the future looked like for that.

**Comment by Cantido** [comment]
@drusepth created the page, I'm not sure if he has a vision for it or anything. He just wanted to see how many people were signing up.

**Comment by drusepth** [comment]
Ha, someone found it! I have no qualms keeping them public for now, as @Cantido said the nature of aggregating data leads to non-personalized trends that are useful to analyze. So far, it's been pretty helpful in determining how users are using locations/items. Eventually we'll probably want legitimate admin functionality (whatever that may be) and will probably want to limit it to some trusted users, but for now I welcome any and all kinds of data analysis as long as it doesn't expose individual user data. :)

**Comment by drusepth** [comment]
We'll hopefully add some more stats to the admin panels eventually, but for now they'll stay public and accessible to everyone in the spirit of transparency. :+1:
