### ISSUE TITLE
Serendipitous occasionally causing builds to fail

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#138]
When Serendipitous picks a content field to ask about, but that field does not have a question in the locale file, it doesn't show a card. That breaks a feature test that expects the card to appear. We need to either make sure Serendipitous can always show a question, or disable the test.

**Comment by drusepth** [comment]
It might be a good idea to somehow limit Serendipitous to only ask about fields that it can generate a question for. The naive approach to this would be to just throw the question generation into a loop until one is present, but we can probably do something better than that. :)

**Comment by drusepth** [comment]
This has been fixed sometime in the past 2 years. 👍
