### ISSUE TITLE
Content groupers need cleaned up

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#143]
The content groupers models are getting a bit out of hand. At the very least, their models should probably be generated at runtime from the `relates` calls, rather than just having a directory full of a bazillion content groupers.

**Comment by Cantido** [comment]
We could probably put all the helpers into a single file or module. Praise Ruby.

**Comment by drusepth** [comment]
As of #912 and custom link fields (putting link data directly into `Attribute` models), we no longer use content grouper models. They haven't been deleted yet, but they're deprecated and on the way out -- so this issue seems moot now. :+1:
