### ISSUE TITLE
On touch, can't use the menu

### ISSUE THREAD

**Issue by ViKomprenas** [indentlabs/notebook#144]
On a touchscreen device, tapping on the menu icon in the top-right will open it as expected, but tapping on any menu option just dismisses the menu.

**Comment by mpigsley** [comment]
@drusepth correct me if I'm wrong but I believe this is a non-issue in https://github.com/indentlabs/notebook/pull/133

**Comment by drusepth** [comment]
This should be fixed in #133. I tested on my Lenovo Yoga (laptop) and a Nexus 5X (phone). Don't have a tablet to test with though.

**Comment by Cantido** [comment]
@drusepth if you could help me figure out how to get it tested on a mobile device, I have a Nexus 7 I can test on. We could also use Chrome developer tools to mock a mobile device.

**Comment by drusepth** [comment]
This should be fixed now that #133 is live. @ViKomprenas Can you confirm at your convenience that things are working for you now?

**Comment by ViKomprenas** [comment]
This is closed, but now the UI is [flooded](https://i.imgur.com/AWPLRNd.png). I'll open a new issue.

**Comment by ViKomprenas** [comment]
See #155.
