### ISSUE TITLE
Need naming scheme for content type groups

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#146]
So we basically have three "types" of content types with #133:

* "Basic" pages: Universes, Characters, Locations, and Items
  * These content types will be always enabled for all universes
  * "Trial" users will be able to create some large amount of these without paying the $20 signup fee

* "Advanced" pages (to be named): Creatures, Races, Religions, Groups, Magics, Languages, etc
  * These content types will be toggle-able on/off per-universe (#113)
  * These are the content types future updates will most likely bring (Worlds, Quests, etc)
  * These content types are unavailable to "Trial" users

* "Collective" pages (to be named): Scenes, Plots
  * Content types that basically aggregate other pages together to let users _do something_ with pages
  * Will likely have close integration with niche apps (e.g. editor that walks you through writing each of your scenes)

In the UI right now they're just labeled as "Core Pages", "Extended Pages", and "Extended Extended Pages". They could definitely use better, more descriptive names.

**Comment by Faustyna** [comment]
I like 'Core pages' and even 'Extended' but the last one needs a re-name. 'Collective' works for that, I'd think.

**Comment by Cantido** [comment]
I like Core, Extended, and Collective. Basic/Advanced doesn't feel too good to me nowadays, the words feel too "monetized."

**Comment by drusepth** [comment]
Lets go with Core/Extended/Collective for now. We can always change them later. Thanks, guys! :+1:
