### ISSUE TITLE
App should use global markdown singleton

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#148]
In the `content/_show` partial we instantiate a new markdown renderer every time we show some markdown-able content. We should probably initialize this in the app and use a singleton from this partial instead.

```
        <%
          markdown = Redcarpet::Markdown.new(
            Redcarpet::Render::HTML.new(
              with_toc_data: true,
              safe_links_only: true,
              filter_html: true
            ),
            autolink: true,
            tables: true,
            strikethrough: true,
            superscript: true,
            underline: true,
            highlight: true,
            footnotes: true,
          ) %>
```

**Comment by Cantido** [comment]
I was worried about thread safety, but it looks like they recommend this sort of use, so I'm guessing that's not a problem :smiling_imp:
