### ISSUE TITLE
Content is not sharable

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#15]
Characters have a "Share this character" option in their drop-down menu, but it doesn't work. Currently, you can only share content by making the universe public. Make the "Share this character" link work.

**Comment by Cantido** [comment]
Idea: the "Share this character" link opens a small dialog with a copy-pasteable link in it.

**Comment by drusepth** [comment]
I like the modal. I think for this issue we need to 

- [ ] add `privacy` field to characters/locations/items
- [ ] add modal that pops up when someone clicks the "Share this X" dropdown button
- [ ] allow modifying either universe privacy or per-content privacy from that modal (with toggles), and if either is public then the content is public
- [ ] throw in a copy-pasteable link
