### ISSUE TITLE
Content header images need optimized

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#150]
They're currently quite large. We should probably have trimmed versions for cards/headers that don't require loading the entire image.

**Comment by mpigsley** [comment]
I can try to do some ffmpeg magic on them. That's the first thing that I noticed when I checked out the new live version.

**Comment by drusepth** [comment]
That'd probably be good. I would have just jumped in and resized things smaller, but I'm not sure how to handle potentially-very-large screen sizes, since we scale the images to the screen width. I'm not very familiar with the common methods to solve this.

**Comment by Cantido** [comment]
With my content dashboard maximized, the images are 564x373. The biggest optimization that we can make is to just cut down the resolution to something a little closer to that size. Currently one of the images is 5257x3474, so there is lots of room for improvement.
