### ISSUE TITLE
Not Rendering Markdown Bullet Points

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#154]
For some reason materialize has `list-style-type: none;` on all list elements which removes the bullet points from the markdown.

### Actual Markdown Output
<img width="634" alt="screen shot 2016-11-02 at 9 35 45 am" src="https://cloud.githubusercontent.com/assets/3017491/19932971/e6ff324c-a0df-11e6-94b3-b8dac0b8af10.png">

### Expected Markdown Output
<img width="641" alt="screen shot 2016-11-02 at 9 08 31 am" src="https://cloud.githubusercontent.com/assets/3017491/19932991/f832d64a-a0df-11e6-8183-b2118e6a8a22.png">

**Comment by Cantido** [comment]
It looks like to turn those back on, we need to add the `browser-default` class to the `ul`: http://materializecss.com/helpers.html#browser-default.

**Comment by drusepth** [comment]
So we actually generate those `ul` from within our markdown engine which doesn't give options to pass a class through, so I went ahead and just overrode the classes manually when in a `markdownable` parent. There might be a better way, but at least lists work currently.
