### ISSUE TITLE
On a tablet, the UI is very cluttered

### ISSUE THREAD

**Issue by ViKomprenas** [indentlabs/notebook#155]
[Screenshot.](https://i.imgur.com/AWPLRNd.png) 9.7" iPad Pro, Safari.

I'd suggest making the sidebars toggleable. That should resolve this.

**Comment by mpigsley** [comment]
I feel that the interface on a desktop is cramped as well. I'm starting to think the right side column should be either removed or moved somewhere else. Doing something with that column could also resolve #170.

**Comment by LarrySawyer** [comment]
I'm working on some new layout ideas with the goal of taking care of issues like this and #170. I'll hopefully have something to show in a few days.

**Comment by drusepth** [comment]
Sidebar is now toggleable, the navbar has been cleaned up, and the interface should be a lot less cramped on tablets. 

![2019-01-09-125743_582x846_scrot](https://user-images.githubusercontent.com/538235/50921656-3272e900-140e-11e9-876f-01bdc8d851f8.png)

![2019-01-09-125755_597x585_scrot](https://user-images.githubusercontent.com/538235/50921664-356dd980-140e-11e9-9f1a-14b306b8be3a.png)
