### ISSUE TITLE
Home Page - Mentions old pricing model

### ISSUE THREAD

**Issue by LarrySawyer** [indentlabs/notebook#157]
The home page still says "Access for life / Signing up for Notebook is just like buying a notebook: one payment and it's yours for life." in the 12-box benefits grid, instead of reflecting the new monthly payment model.
![Screen shot](https://cloud.githubusercontent.com/assets/8932810/19966158/ee9021a8-a1a0-11e6-8665-0b03920b2377.png)

**Comment by drusepth** [comment]
Good catch. :snowboarder:
