### ISSUE TITLE
Adding a Custom Attribute Clears Unsaved Content

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#158]
When creating a custom attribute, might want to save the rest of the fields with it so they don't get cleared.

I know it says `Please save any changes before adding a field. It will refresh the page and any changes in your form will be lost.`, but it would be nice to not have to do that.

**Comment by drusepth** [comment]
We could (should) probably create that field with `remote: true` and then just either get back the field name from the response or build it ourselves and add it to the form manually. The only downside is that if the field doesn't create for some reason, a user could theoretically type a bunch into the field and submit, only to see it all disappear.

But yeah, I agree. :+1:

**Comment by drusepth** [comment]
Since category/field editing now occurs on its own dedicated page, this shouldn't be an issue anymore.
