### ISSUE TITLE
Error When Deleting Custom Attribute

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#161]
Getting a 500 error when I go to delete a custom attribute. I wasn't able to repro this locally so you might need to dig in the production logs.

![](http://g.recordit.co/yFjfCDvGgE.gif)

**Comment by drusepth** [comment]
No idea how this worked locally, actually. Fixed in https://github.com/indentlabs/notebook/commit/e8afa326b3fceb313ee84a96fc25a6a12571928f
