### ISSUE TITLE
Custom attributes can duplicate core attribute names

### ISSUE THREAD

**Issue by DarkFieryVortex** [indentlabs/notebook#163]
I was wondering if I could add a custom field to a core attribute, so I tried to add a field to Overview and now I have two Overviews. Perhaps a name uniqueness check should be added?

![core_attr_dupe_example](https://cloud.githubusercontent.com/assets/22652163/19990854/5bb07722-a207-11e6-8ceb-88adcfc9a2d7.png)

**Comment by Cantido** [comment]
Good catch. @mwerner, do you think this will cause any issues if a tab name duplicates an existing one? We wouldn't want to accidentally delete the built-in Overview tab :joy_cat:

**Comment by mwerner** [comment]
Right now, the built in categories are statically listed in a configuration file. When the card is rendered, it lists all the static categories, then loads custom ones afterwards. There is no way to remove the built in tabs, but unfortunately it would require a bit of extra work to merge built in tabs with custom tabs.

**Comment by Cantido** [comment]
I understand. I think for now we can call this a feature, instead of a bug :smirk_cat:

**Comment by mwerner** [comment]
Yeah, it just gets super difficult to reliably align the custom category with the same name as the built in tab. You can do some sort of matching, but it's going to introduce a bunch of other "where did my custom attribute go?" kind of bugs, which are tougher to pin down.

The other direction you can do is to reduce the number of built-in static definitions in the config, and use ruby to seed a new user's database with "suggested" categories, so then all the tabs would actually be custom tabs and behave as such.
