### ISSUE TITLE
More resolution to friends & enemies

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#164]
We have some feedback on more complex relationships with more resolution than best friend or worst enemy. Essentially it breaks non-familial relationships down into

 - People with a positive relationship with this character
 - People with a neutral relationship with this character
 - People with a negative relationship with this character

Best friend and Archenemy are definitely still valid, but by definition you can only have one best friend. This also sounds relevant to factions, if we add support for those.

**Comment by drusepth** [comment]
Since users can now create their own fields and link other pages with them, I'd say this is now done in a very general sense.
