### ISSUE TITLE
Content from filtered universes shows up in drop-downs

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#165]
A user posted this image on our Reddit thread, showing how a city from a different universe (TestCity) was showing up in their drop-downs even though their universe filter should have hidden it.

![image](https://cloud.githubusercontent.com/assets/1505603/20031741/594cf340-a34a-11e6-821b-25a85e70ede3.png)

**Comment by drusepth** [comment]
I'd like to also scope content to the same universe when editing something with a universe set but not scoped to a universe, but it's a bit more difficult to mix a universe filter with a form that we don't know whether (the universe, particularly) has been changed. Perhaps later, though.

As for this, I added an `in_universe(universe)` scope to all content that filters it to a particular universe if one is given, or returns everything if universe is nil (e.g. `@universe_scope` is nil). This is live and looks like it's working well, so I'll close this. :+1: Thanks for reporting it though :)
