### ISSUE TITLE
Migration issues and what I did to fix them.

### ISSUE THREAD

**Issue by LeBodro** [indentlabs/notebook#166]
I found out this morning about notebook and tried to setup the project.

Since it's my first day with notebook, rails and ruby, I prefer not doing a pull request and just pointing out what I found:

First, that's what happened when I tried to migrate, for both 'magics' and 'languages' tables migrations:
```
== 20161016213335 CreateLanguages: migrating ==================================
-- drop_table(:languages)
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: languages: DROP TABLE "languages"
```

What I did was to remove the table dropping (ex:`drop_table :languages`) at the beginning of these files:
```
20161016211328_create_magics.rb
20161016213335_create_languages.rb
```
I rolled the migrations again and everything went smooth.

If anyone knows of a better solution, you are welcome to comment.

**Comment by drusepth** [comment]
Ah no, you're right to do so. I'll remove those lines from the migration; they were only there because our production DB already had those tables from an early beta test. Thanks for pointing this out, I'll get it sorted out. :)
