### ISSUE TITLE
Content Page Navigation Overflows When Editing

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#170]
In the image the notes and any custom fields are cut off. That photo is from a browser is sized to a 1440px width.

<img width="864" alt="screen shot 2016-11-06 at 4 57 06 pm" src="https://cloud.githubusercontent.com/assets/3017491/20042591/557cd8d6-a442-11e6-89a1-b829624b3311.png">

**Comment by LarrySawyer** [comment]
I'm working on some new layout ideas that should solve this, but you should currently be able to scroll back and forth on that category navbar. Maybe there should be something to better indicate that?

**Comment by mpigsley** [comment]
Oh nice. Yeah, not sure how to make that more noticeable. I did notice that the scrollbar is misaligned in chrome FWIW.

![](http://g.recordit.co/O8kEakAyf0.gif)

**Comment by drusepth** [comment]
@LarrySawyer Any chance you've got any of those design ideas to show off? Otherwise I'll probably tackle this in the relatively near future.

**Comment by drusepth** [comment]
This is no longer the case in the new design. Tabs are vertically displayed on the right, so this shouldn't be an issue anymore.

![2017-03-01-201107_727x522_scrot](https://cloud.githubusercontent.com/assets/538235/23479090/38b785e2-febb-11e6-8304-65f1d3614ff5.png)
