### ISSUE TITLE
No Such App

### ISSUE THREAD

**Issue by Omuck3** [indentlabs/notebook#172]
Hi.  When I tried to go on notebook.ai(for the first time in a while), the page just says "No Such App."

Is this an issue on my end?

**Comment by mpigsley** [comment]
Uh oh... I'm seeing that too.

**Comment by drusepth** [comment]
Hey guys, no worries. Looks like there were some issues with Heroku Billing (TL;DR I just moved and the card couldn't run with my old address) but it's resolved now. Site's back up and nothing was lost (other than uptime). 

Should all be well now!
