### ISSUE TITLE
Uptime report

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#18]
I bet there's some free heroku add-on that reports app uptime. We should probably throw up a status page with uptime reports to show users their data is always readily available when inspiration hits.

**Comment by drusepth** [comment]
Looks like it might just be https://elements.heroku.com/addons/stillalive ($9/mo) and https://elements.heroku.com/addons/statuspage ($29/mo) for now -- probably need to look outside of the heroku add-on stack.

**Comment by drusepth** [comment]
Free solutions:

- https://cachethq.io/
- http://staytus.co/

**Comment by mpigsley** [comment]
You could run a small app on Firebase for free and link it to a subdomain.. like `status.notebook.ai`.
