### ISSUE TITLE
Landing page cards don't always align

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#181]
I've noticed this on a couple different screen sizes. Here's a screenshot of the homepage on an iPad mini:

![2017-02-06-113540_760x755_scrot](https://cloud.githubusercontent.com/assets/538235/22645790/b5b2c88a-ec60-11e6-8e01-b12e5c1bafc8.png)

Dunno what's causing this, but it also happens on the logged-in dashboard for the similar view of cards there, too.

**Comment by mpigsley** [comment]
That first card is longer than the second card. The third card in this case will flow underneath the parent with the smaller height. Those styling rules are built into the library you are using (I've noticed it on the edit item views as well). Easiest solution is to make those cards a consistent height. Harder solution is to fix those css flow rules.

**Comment by drusepth** [comment]
I'd actually be open to moving to a new style library, especially if we're thinking about a larger redesign. Materializecss was great when I first started using it (maintained and comparable in features to other material design libraries at the time), but it seems to have staled and the feature collection isn't quite as comparable anymore. 

Do you have any libraries you'd recommend looking at?

**Comment by mpigsley** [comment]
I find myself starting off with lightweight libraries and building on top of them. Especially since complex interfaces beg custom css. My favorite lightweight library is http://getskeleton.com/

**Comment by drusepth** [comment]
@sn31 Let me know if you need any help setting up the rails app. The readme's pretty comprehensive in its steps. 👍

**Comment by drusepth** [comment]
This was fixed by @sn31. (Thanks!) :tada:
