### ISSUE TITLE
Character race redundancy

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#183]
On characters we have "race" and "races" fields, one text and one link. We should probably do another migration to create a Race for everyone for whatever race is listed in the "race" field and then remove it.

**Comment by derwild** [comment]
Keep in mind here, that this could be a potential problem for users with the free plan.
Because they only don't have access to the Races class, they can at least use the Races textfield to add a race

**Comment by drusepth** [comment]
Since users can now customize what fields they do/don't use and can link any kind of page from any field (or just write text), I think this can be closed.
