### ISSUE TITLE
Relation objects aren't deleted when the objects owning them are deleted

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#190]
To reproduce:

* Create a character Alice and a separate character Bob
* Link Bob as Alice's sibling in the Family tab
* Delete both Bob and Alice
* You will see 2 Siblingship objects remain in the database.

Expected:

* These Siblingship objects should be deleted when either of the related objects are deleted

Note:

* Deleting either Alice or Bob should also delete both Siblingship objects, but should obviously not delete the Alice character (if deleting Bob) or the Bob character (if just deleting Alice).

The fix should include test(s) for the above cases.

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42411724)](https://www.bountysource.com/issues/42411724-relation-objects-aren-t-deleted-when-the-objects-owning-them-are-deleted?utm_source=42411724&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by drusepth** [comment]
There is a $5 bounty for completing this issue (via Bountysource).

[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=42411724)](https://www.bountysource.com/issues/42411724-relation-objects-aren-t-deleted-when-the-objects-owning-them-are-deleted?utm_source=42411724&utm_medium=shield&utm_campaign=ISSUE_BADGE)

**Comment by Slickytail** [comment]
I'm going to try this one

**Comment by babu-thomas** [comment]
Hi @drusepth I'd like to try this one. I have set up the project locally using Docker. I am a beginner to Rails and Ruby. Do you have any suggestions which files I should look into to get started on this issue?

**Comment by drusepth** [comment]
Hey @babu-thomas, welcome! Happy to help however I can.

To start, I'd browse through the `Character` class (app/models/character.rb) to get a sense of what defines a Character (which you'll create two of for the above reproduction steps). 

Relationships are set up in a bit of a complex way, but this is a top-down breakdown of what it looks like. You can dive into the `relates` method in the `HasContentGroupers` concern to see how this works.

In short, a `Character` has many relations on it: e.g. siblings, parents, children, etc. Each of these relations have their own model (e.g. Siblingship, Parentship, BestFriendship, etc -- they usually end in -ship and you can find them all in the app/models/content_groupers directory). Taking the Siblingship class as an example, it has a `belongs_to :character` association (tying it to one character) and a `belongs_to :sibling, class_name: 'Character'` association (tying it to the other character), implying that one character is the sibling of another. Since siblings are a two-way association (if Alice is Bob's sibling, that means Bob is Alice's sibling too), we have some extra logic in an `after_create` block on the `Siblingship` model to go ahead and reciprocate that association (so: if you, in the UI, say that Alice is Bob's sibling, we automatically mark Bob as Alice's sibling for the user -- so they don't have to link both manually). We also have similar logic in the `after_destroy` block: if a user says Alice is no longer Bob's sibling (by deleting that siblingship object tying them together), we automatically delete the reciprocal relationship of Bob --> Alice, too. If you look at has_content_groupers, you can see how this works under the hood (with Siblingships as an example in the comments, actually).

The relevant code to change is (or is around)
```
      # Siblingships
      has_many connecting_class_name

      # Siblings
      has_many relation,
        through: connecting_class_name
```
in has_content_groupers, which Character includes in character.rb. A character has_many siblingships, an we want to make sure that if a character is deleted, its siblingships (and other relations set up through the `relates` method) are also deleted. I'd check out [this documentation](http://guides.rubyonrails.org/association_basics.html) to start. :)

Does that help? It's a lot of information, but should be enough to start with!

**Comment by babu-thomas** [comment]
Thanks a lot! I will start looking into the documentation and the files you mentioned. Will update here when I have something.

**Comment by babu-thomas** [comment]
I think I made some progress @drusepth. I read the documentation you linked and got to know the `:dependent` option for `has_many` association. I then made the following change in `/app/models/concerns/has_content_groupers.rb` -
```diff
       # Siblingships
-      has_many connecting_class_name
+      has_many connecting_class_name, dependent: :destroy
 
       # Siblings
       has_many relation,
```
Branch with changes committed [here](https://github.com/babu-thomas/notebook/tree/issue%23190).
Reproducing the issue after the fix now gives -
   * Create Alice and Bob
```
irb(main):003:0> Character.all
  Character Load (1.0ms)  SELECT "characters".* FROM "characters"
=> #<ActiveRecord::Relation [#<Character id: 8, name: "Alice", role: "", ... >, 
   #<Character id: 9, name: "Bob", role: "", ... >]>
```
  * Link Bob as Alice's sibling
```
irb(main):004:0> Siblingship.all
  Siblingship Load (0.5ms)  SELECT "siblingships".* FROM "siblingships"
=> #<ActiveRecord::Relation [#<Siblingship id: 11, user_id: nil, character_id: 9, sibling_id: 8, created_at: "2017-10-16 18:46:00", updated_at: "2017-10-16 18:46:00">,
   #<Siblingship id: 12, user_id: nil, character_id: 8, sibling_id: 9, created_at: "2017-10-16 18:46:00", updated_at: "2017-10-16 18:46:00">]>
```
  * Delete Bob
```
irb(main):005:0> Character.all
  Character Load (0.8ms)  SELECT "characters".* FROM "characters"
=> #<ActiveRecord::Relation [#<Character id: 8, name: "Alice", role: "", ... >]>
```
```
irb(main):006:0> Siblingship.all
  Siblingship Load (0.3ms)  SELECT "siblingships".* FROM "siblingships"
=> #<ActiveRecord::Relation []>
```
The Siblingship objects have been deleted from the database. Is this the right way to do it?

**Comment by drusepth** [comment]
Nice! The `:dependent` option is exactly what I was alluding at without saying so. :)

The way you tested looks good. The only other thing I'd test for functionality (but is probably fine) would be to double-check the `siblings` relation as well after deleting the siblingship. Before deleting the relation, we'd expect `Character.find_by(name: 'Alice').siblings` to return an array containing the Bob character (as opposed to `Character.find_by(name: 'Alice').siblingships` returning an array of the Siblingship object). After deletion, calling `.siblings` on either character should return an empty array.

Since this code is used across all relations including one-way relations (e.g. children, parents, etc), I'd also double-check this solution looks logical for those. For example:

* Create a character Carol and a character David
* Mark Carol as David's mother
  * This creates a Mothership object tying Carol to David, and a Childrenship object typing David to Carol
* Delete Carol
  * This should delete Carol, the Mothership object, _and_ the Childrenship object
  * This should _not_ delete David

I imagine this'll still work good and well, but something to double check.

When all is working, I think we can write a quick test with the original repro steps and close this out. Good job (and thanks!)! :)

**Comment by babu-thomas** [comment]
Thanks, I never thought to check the `siblings` object! I am not entirely convinced yet that I fully understand how all the relationships are laid out in code. I will check for the cases you mentioned and also search for how to write tests.

**Comment by drusepth** [comment]
Hey @babu-thomas, there was a $5 bounty attached to this issue through BountySource. I've never used them before (I was using this issue as a test-run) but you should be able to claim it from [this link](https://www.bountysource.com/issues/42411724-relation-objects-aren-t-deleted-when-the-objects-owning-them-are-deleted). I'm not sure what the process is like, but I'm happy to verify/confirm anything needed along the way!

Thanks!

**Comment by babu-thomas** [comment]
Sweet! Will let you know how it goes.

**Comment by babu-thomas** [comment]
Seems that BountySource is currently having an issue with Github logins. https://github.com/bountysource/core/issues/1147. Will try it out later. Thanks!
