### ISSUE TITLE
Custom categories don't get cleared after the last field gets removed.

### ISSUE THREAD

**Issue by surashu** [indentlabs/notebook#191]
### Expected behavior
After deleting the last field in a custom category, the category should cease to be remembered by the system because it will keep things clean.
### Actual behavior
While typing a new category name, the old ones are still getting suggested.
### Steps to reproduce the behavior
1. Add a new custom category anywhere and add custom fields.
2. Remove all the custom field causing the custom category to be removed from the sidebar.
3. Try adding a category and type the first letter of the last category made in step 1.
4. It will still show up and is suggested when it should have been deleted after the last custom field got deleted.

**Comment by drusepth** [comment]
Ah, thanks for pointing this out. Good catch!

**Comment by drusepth** [comment]
This should be fixed for all attribute deletions moving forward. Running a script to wipe out any empty categories that currently exist in production as well.

Thanks for the bug, @surashu! :+1:

**Comment by surashu** [comment]
That's awesome, thanks! 🎉
