### ISSUE TITLE
Plan Creatures

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#21]
Should cover planning monsters, animals, mythological creatures, and other living things that aren't necessarily "characters".

**Comment by drusepth** [comment]
Starting a general outline of the fields we should expect here... Probably needs quite a bit of polishing/adding/removing before finalized.

```
Overview
  Name
  Description
  Type (animal, plant, etc)
  Other names
  Universe
Looks
  Physical description
  Weight
Traits
  Preferred habitat
  Found in (link to Locations)
  Reaction to humans
  Maximum speed
Habits
  Food sources
  Migratory patterns
  Reproduction
<something>
  Symbolisms
```

**Comment by drusepth** [comment]
Done on `content-expansion` branch.

**Comment by Cantido** [comment]
How would this relate to Races? And would a Character be able to be a type of Creature?

It sounds like we're building an ontology here. This may benefit from a nice long design session to think out the easiest way to relate everything.

**Comment by drusepth** [comment]
@Cantido Just saw that comment. Right now Characters have a `races` field, but I'd say eventually (after #116) we'd want them to be able to link races or creatures.

Also, this is live and looking good. Let's open up any new iterations on it as new issues :+1:
