### ISSUE TITLE
Plan Groups

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#22]
Should cover planning businesses, governments, activist groups, etc. Basically any large grouping of (named or non) characters.

**Comment by drusepth** [comment]
Better name for this is "Plan Groups".

**Comment by drusepth** [comment]
Starting a general outline of the fields we should expect here... Probably needs quite a bit of polishing/adding/removing before finalized.

```
Overview
  Name
  Description
  Other names
  Universe
Hierarchy
  Supergroups (link to Groups)
  Subgroups (link to Groups)
  Sistergroups (link to Groups)
Members
  [List of Membership relations to Characters, each with a "rank"/"title" field on it]
    e.g. "Bob [Sargeant] \n Carol [Officer]"
Purpose
  Motivation
  Goal
  Obstacles
  Risks
```

**Comment by T4nky** [comment]
Hi! I messaged you on Reddit to see if you needed any help (I'm u/gmrm4n, btw.) I was wondering if I could work on some of the code. I also have some additions. They'll be shown by being between double asterisks.

Overview
  Name
  Description
  Other names
  Universe
**Politics**
  **Allies (link to Group and/or People**
  **Enemies (link to Group and/or People**
  **Rivals (link to Group and/or People**
  **Clients (link to Group and/or People**
Hierarchy
  **Description of Hierarchy (text)
  **Commander (link to People)**
  **Headquarters/Capitol (link to Place)**
  Supergroups (link to Groups)
  Subgroups (link to Groups)
  Sistergroups (link to Groups)
  **Ranks (determines the options for "rank"/"title" field**
**Territory**
  **Headquarters/Capitol (Link to Place, auto-include entry(s) in Hierarchy**
  **Controlled area (Link to place)**
**Equipment**
  **Equipment overview (text)
  **Standard Equipment (link to Items)**
  **Special Equipment (link to Items)**
  **Equipment Suppliers (Groups and/or People, will fill in a corresponding section for them called Clients**
Members
  [List of Membership relations to Characters, each with a "rank"/"title" field on it]
    e.g. "Bob [Sargeant] \n Carol [Officer]"
Purpose
  Motivation
  Goal
  Obstacles
  Risks

**Comment by drusepth** [comment]
@T4nky Those are some great additions. I added my comment above to add them in so we can keep a singular reference list when we get started on this.

One comment though is that it's a great idea to link to multiple types (I can already see things that could link to Locations/Groups or Groups/Characters), but right now we don't actually have a way to do that. We should definitely be thinking of a nice way to do it though, now that we're starting to get a better catalog of content types to plan out, instead of the original people/places/things triumvirate.

**Comment by T4nky** [comment]
Totally fine.  I know just enough to understand how hard programming can be.

**Comment by drusepth** [comment]
Woop, this is live and looking good. We can open new issues on iterations, but lets close this one since it's live. :+1:
