### ISSUE TITLE
Plan Languages

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#23]
Build, plan, and work with constructed languages. Needs research into what all would be useful; see http://reddit.com/r/conlangs for research/inspiration.

**Comment by drusepth** [comment]
Starting a general outline of the fields we should expect here... Probably needs quite a bit of polishing/adding/removing before finalized.

```
Overview
  Name
  Description
  Other names
  Universe
Info
  Origin
  Sounds
Words
  <Some kind of custom dictionary/translator here -- needs fleshed out>
Spoken by
  Characters
  Races
  Locations
```

**Comment by babelfish** [comment]
So, the issue with languages is you need to either be very, very general and provide a few generic sections along with the ability to add an arbitrary number of custom sections, or you need to be very, very specific. There's really no in-between that's going to work for the majority of conlangs, there's just too much variety in what they'll need. Custom fields would be especially important for the lexicon. If we want Lexicons to be a first class feature that's a whole additional conversation separate from Language planning.

An IPA table would be nice, but as an optional addition to a plain text Phonology section. It would be cool if it could be inserted into the Phonology section. Maybe a button that inserts an empty markdown IPA table into the edit box?

Comments on the outline:
```
Overview
  Name
  Other names
  ~~Description~~ (the whole thing is a description of the language, maybe an Introduction or Abstract field)
  Universe
Info
  ~~Origin~~History (seems more general than origin)
  Typology
  Dialectal Information
  Register
Phonology (markdown text field prefilled with sample headers like:)
  Consonants
  Vowels
  Allophony
  Phonotactics
  Prosody
  Orthography
Grammar (a single, empty markdown field is probably best here, the specific sections that will be needed will simply vary too much language to language and the approach one takes to writing grammars)
Numbers and Quantifiers
Custom Fields
Writing System(s) (would be very helpful if they could upload images here)
Lexicon
  <Some kind of custom dictionary/translator here -- needs fleshed out>
Spoken by
  Characters
  ~~Races~~Cultures
  Locations
```

A real nice-to-have (but likely outside of the initial scope) would be an extension to markdown for creating [interlinear glosses](https://en.wikipedia.org/wiki/Interlinear_gloss).

**Comment by Cantido** [comment]
Are there any "conlang builder"-type applications out there? If folks use spreadsheets, I'm guessing not.

This sounds complicated but it would be really awesome, and I think it could tie into @drusepth's vision of AI-augmented writing. We could do a lot of really cool stuff if we can hook in some AI to a structured con-lang data set.

**Comment by babelfish** [comment]
There's the ConWorkShop site that NeoMahler linked, but working with lexicons is a hard problem, especially if you're doing diachronic conlanging (modeling the changes in a language over time). You'd probably need a graph database for that.

**Comment by Cantido** [comment]
Oh I missed that link. If it's too hard to make a complete solution for conlangs, maybe we could start with a tool that's "good enough" for people who are just breaking into the field? Then we could gather feedback and build up the tool. Basically what would be the minimum viable product for a conlang planner?

**Comment by NeoMahler** [comment]
* Lexicon. No translator needed, just a list of word with translation.
* Phonetics: Vowels and consonants, and how should they be represented 
(for example, [ð] is written as <dh> in my conlang).
* Grammar: a text box (a big one), and let the user put there whatever 
they want.
* And the cultural things noted above: history, where is it spoken...

**Comment by babelfish** [comment]
I think an MVP would include, roughly, the fields I listed, the lexicon editor being the hard part. It doesn't make sense as a simple text field like most content we work with. We need a way to work with tabular data and support custom fields.

**Comment by NeoMahler** [comment]
With "just a list of word with translation" I didn't meant a plain text 
box but some sort of a formulary, and then a list of all entries.

**Comment by drusepth** [comment]
This is awesome feedback. I do think starting with somewhat of an MVP and iterating on it would be the best idea, since it seems like there's an endless road we can go down in specifics.

Taking @babelfish's revised outline above (thanks), here's what I think we should do based on the comments here so far:

```
Overview
  Name
  Other names
  Universe
Info
  History
  Typology
  Dialectal Information
  Register
Phonology
  Phonology (markdown text field prefilled with the following headers:)
    # Consonants
    # Vowels
    # Allophony
    # Phonotactics
    # Prosody
    # Orthography
Grammar
  Grammar
Entities
  Numbers
  Quantifiers
Lexicon
  <Some kind of custom dictionary/translator here -- needs fleshed out>
Spoken by
  Characters
  ~~Races~~Cultures (see #3 below)
  Locations
Notes
  Public Notes
  Private Notes
```

Other notes:

1. The Markdown formatter we have in #124 allows ToC-style IDs on headers, so just having a header (or prefilled headers, as we do above) of e.g. `# Consonants` will allow linking directly to that section by appending `#consonants` to the page URL. We would probably need to do some extra JS to select the proper tab to show as well (e.g. `#consonants` opening `phonology` tab) to take full advantage of this.

2. Having tabs with just a single field in them will automatically expand that field to full-width in the tab, so populating it with some example headers would be a good way to have some additional prompts within a single, big field. We could probably have multiple, consecutive full-width fields (for consonants, vowels, allophony, etc) under the Phonology tab with a little extra Ruby to let fields override how wide they render. Which do you guys think is better?

3. With the current work on custom attributes (#108), it looks like we'll be able to add custom fields (potentially on the fly if not through some outside config) to any tab, instead of needing a Custom Fields tab for them. 

- While Cultures would make more sense than Races in the Spoken By tab, we don't have a Culture content type in progress. Should we 1) just not have a Races link, 2) keep Races as a link, or 3) build out a Culture content type?

**Comment by drusepth** [comment]
As for the lexicon, what do you guys think of an MVP that lives inside the Lexicon tab that's basically just a list of rows (of two columns: word and translation). We can always build out a translator from there, but this at least would provide some easy way to store word-by-word translations.

**Comment by NeoMahler** [comment]
> As for the lexicon, what do you guys think of an MVP that lives 
> inside the Lexicon tab that's basically just a list of rows

As a beginning is good, but be prepared for a requests wave from 
conlangers! ;)

**Comment by babelfish** [comment]
>Having tabs with just a single field in them will automatically expand that field to full-width in the tab, so populating it with some example headers would be a good way to have some additional prompts within a single, big field. We could probably have multiple, consecutive full-width fields (for consonants, vowels, allophony, etc) under the Phonology tab with a little extra Ruby to let fields override how wide they render. Which do you guys think is better?

With #108 either is probably fine, though just using markdown headers allows them to remove some of those fields if they're not using them. The level of detail different conlangers go into varies greatly.

>With the current work on custom attributes (#108), it looks like we'll be able to add custom fields (potentially on the fly if not through some outside config) to any tab, instead of needing a Custom Fields tab for them.

This is better.

>While Cultures would make more sense than Races in the Spoken By tab, we don't have a Culture content type in progress. Should we 1) just not have a Races link, 2) keep Races as a link, or 3) build out a Culture content type?

Ideally, 3. If that's not realistic... maybe reduce this to a simple Demographics field within the Info section where the author can describe where and by whom it's spoken?

>As for the lexicon, what do you guys think of an MVP that lives inside the Lexicon tab that's basically just a list of rows (of two columns: word and translation). We can always build out a translator from there, but this at least would provide some easy way to store word-by-word translations.

It works as a true MVP, but I think if you don't have custom fields most conlangers are going to stick to using spreadsheets. Ideally we'd actually have multiple lexicons per language each with their own unique set of fields. There's a whole bunch of potential metadata we often want to include alongside words and translations: various classifications that depend on the language and part of speech such as noun class (gender), count/mass/collective, animate/inanimate, strong/weak, active/stative, transitivity, etc; IPA representation; etymology; notes and so on.

**Comment by drusepth** [comment]
Done & live.
