### ISSUE TITLE
Viewing someone else's content shows your custom attributes in the sidelinks

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#233]
### Expected behavior
- If a user creates custom attributes on public content, you should be able to see those custom attributes when viewing that content
- If you create custom attributes on your own content, you should not see those custom attributes when viewing someone else's content

### Actual behavior
- Viewing someone else's public content displays your custom attributes in the content sidelinks instead of theirs

### Steps to reproduce the behavior
- Create two users locally
- On the first user:
  - Create a Character
  - Create a custom attribute for it and give it a value
  - Change that character's visibility to public from the share modal
- On the second user:
  - Create a Character
  - Create a different custom attribute for it
  - View the URL of the first user's character
  - Observe that the sidelinks show your custom attribute(s) instead of theirs

For example, I created custom attribute categories for "Plot" and "Rules" on my universes. When I visit someone else's public universe, this is what that universe's sidelinks show:

![2017-10-02-160526_635x483_scrot](https://user-images.githubusercontent.com/538235/31081427-2c8575d4-a78c-11e7-8493-e3901011aec8.png)

**Comment by imacubsfan23** [comment]
Hi drusepth, I'm having a hard time replicating this error. 

I made 2 separate accounts on notebook.ai, made a character on each account (with their own custom categories (not sure if this is what you were referring to), and was able to view the first account's user's custom category. I also repeated this task with universes, and could not replicate the issue.

Tell me if I'm wrong, but this might have been fixed in another pr.

**Comment by drusepth** [comment]
Hey @imacubsfan23 -- very sorry about this; looks like this was indeed fixed by another PR and I didn't keep this issue up to date. I'm going to go do some issue pruning and make sure everything else is up to date now. Thanks for bringing this to my attention.

**Comment by imacubsfan23** [comment]
Hey, no problem. If you happen to know which commit fixed this issue, please let me know, I'd love to see what was done to change it.
Also, by the way, I'm new here and a beginner at open source. This project definitely looks like something I'd love to help with, so if you have any beginner issues you need help with, don't be afraid to tag me in it. If not, I'm watching the repo anyways and I'll see new issues as they appear.
Thanks
