### ISSUE TITLE
"Email has already been taken." message duplicate.

### ISSUE THREAD

**Issue by BrynnMountain** [indentlabs/notebook#235]
### Expected behavior
When creating a new account with an email that already exists, there is a message that displays saying "Email has already been taken". 

### Actual behavior
This message is displayed twice in a row.

### Steps to reproduce the behavior
Create a new account with an email already in use.

**Comment by JorgeAndd** [comment]
Is this still open?
I have no experience with Ruby, but would like to try it

**Comment by drusepth** [comment]
@JorgeAndd This is indeed still open, and should be a pretty good starting point in Ruby/Rails.

Once you get the site running locally (following the instructions in the readme), you should be able to reproduce this by creating a user, and then creating another user with the same email address. 

I'm not sure off hand what causes this (I haven't looked), but one small tidbit of advice I'd offer is that `flash` is a special hash that gets set while processing a response, and gets displayed in the view if either `flash[:alert]` or `flash[:notice]` are set. They're in `app/views/cards/ui/alert` and `app/views/cards/ui/notice`, both rendered in `app/views/layouts/application`. 

Hope that helps! Happy to answer any questions you have. 👍

**Comment by JorgeAndd** [comment]
I noticed the error message is also duplicated when the email is left blank.

Did some research and looks like the problem is with Devise.
https://stackoverflow.com/questions/13897844/how-to-remove-duplicate-validation-errors
https://github.com/lynndylanhurley/devise_token_auth/issues/892

I will continue trying to find where is the problem, but will be glad if you have any suggestions.

**Comment by drusepth** [comment]
Good call. According to [this answer](https://stackoverflow.com/a/13897948), we might be able to remove the `validatable` bit of Devise (or remove our own email validation).

From our user.rb:
```
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :email, presence: true, uniqueness: true
```

Looks like we don't need both, but I'm not sure off hand what the implications are of removing either, or which one we'd want to keep/remove. Might be worth looking into what `:validatable` gives us and decide if it's worth keeping over just doing our own validations. But I think you're right: we probably have the same issue as the guy at that SO link, and we probably need to do the same: removing one. 👍

**Comment by JorgeAndd** [comment]
Did some tests here.

Removing `validatable` from devise does indeed stops the duplicated message, but we lose validation on password. 
So, I tried removing the `validates` lines, keeping the devise validation, and it still does email uniqueness and presence validation.

Do you think removing our own validation is enough to fix the issue?

**Comment by drusepth** [comment]
I think as long as our `validates :email` line is redundant with what's provided in Devise's `:validatable` add-in, we should be good to remove it. Does the duplicate message disappear in that case?

If so, happy to review/merge a PR removing it!

**Comment by JorgeAndd** [comment]
I think it is indeed redundant. 
I made a PR, please check if everything looks fine :)
