### ISSUE TITLE
rake aborted!

### ISSUE THREAD

**Issue by lloyd094** [indentlabs/notebook#236]
### Expected behavior
Following instructions for installation locally (Linux), I run into this error on the last bit.

### Actual behavior
```shell
rake db:migrate
rake aborted!
ActiveRecord::StatementInvalid: Could not find table 'religious_locationships'
```

### Steps to reproduce the behavior
Follow the instructions provided at the bottom of your readme.

**Comment by drusepth** [comment]
Hey, thanks for pointing this out. Looks like one of the old migrations (adding religious_locationships) wasn't named correctly, so it wasn't running. If you want to try again on the latest `master`, it should work for you now.

**Comment by lloyd094** [comment]
That seems to have fixed the issue. Thanks!
