### ISSUE TITLE
500 When Deleting Custom Category Attribute

### ISSUE THREAD

**Issue by mpigsley** [indentlabs/notebook#245]
### Expected behavior

The attribute would be deleted from the custom category.

### Actual behavior
![](http://g.recordit.co/M7VteXcma7.gif)

### Steps to reproduce the behavior

Not sure exactly what the cause of this is. In the gif, I have two attributes labelled `Attack` which could be the problem. Or it could just be custom category attributes in general.

**Comment by heydonovan** [comment]
Just recreated the issue on my local machine. Will look into later!

```
web_1  | Started DELETE "/plan/attribute_fields/1" for 172.19.0.1 at 2017-10-26 14:26:34 +0000
web_1  | Processing by AttributeFieldsController#destroy as HTML
web_1  |   Parameters: {"authenticity_token"=>"uck+vJgzblMLtBsR2Uj0aIeFL/J7dc9azno4jV80been7bW/gQUFjlF0lUGs1ZbzYYyuCMKSLkQW/0ouRbW5mw==", "id"=>"1"}
web_1  |   User Load (2.4ms)  SELECT  "users".* FROM "users" WHERE "users"."id" = ?  ORDER BY "users"."id" ASC LIMIT 1  [["id", 1]]
web_1  |   AttributeField Load (1.9ms)  SELECT  "attribute_fields".* FROM "attribute_fields" WHERE "attribute_fields"."id" = ? LIMIT 1  [["id", 1]]
web_1  | Completed 500 Internal Server Error in 11ms (ActiveRecord: 4.3ms)
web_1  |
web_1  | NoMethodError (undefined method `universe' for #<AttributeField:0x007ff1464d1978>):
web_1  |   app/services/permission_service.rb:32:in `content_has_no_containing_universe?'
web_1  |   app/authorizers/content_authorizer.rb:27:in `deletable_by?'
web_1  |   app/controllers/content_controller.rb:200:in `destroy'
web_1  |   app/controllers/attribute_fields_controller.rb:5:in `destroy'
```

**Comment by GayKiwi** [comment]
This looks like its being worked on at the moment. The work has changed this to create the 500 error message on creation, then provides a 404 error on deletion.

At both stages, the operation actually happens, but requires the user to back track and reload the page to display these changes.

Chrome: Version 61.0.3163.100 (Official Build) (64-bit)

**Comment by drusepth** [comment]
Ah yes, I had pushed up an update last night that I wanted to verify working before closing this. It's actually working (creating and/or deleting) for me, but I'll look into the issues you're seeing. Thanks for the heads up.

**Comment by drusepth** [comment]
This should be fixed now, as I can no longer replicate the issue. Can anyone else?

**Comment by mpigsley** [comment]
Works for me @drusepth!

**Comment by drusepth** [comment]
Woo!
