### ISSUE TITLE
How can I delete the account?

### ISSUE THREAD

**Issue by sakuraiwanaga** [indentlabs/notebook#247]
### Expected behavior
I have created an account from the website. (The link is below)
`https://www.notebook.ai`
Since, I thought I want delete the account, there weren't any ways to do this.
Or maybe I couldn't find.

**Comment by drusepth** [comment]
Hey @sakuraiwanaga, right now the only way to delete an account is to email support at andrew@indentlabs.com. If you send an email from the email address tied to your account, I'd be happy to delete it for you!
