### ISSUE TITLE
Translate landing page and site to Spanish

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#248]
Translating the site will have implications for #240, but I think it's worthwhile to start collecting translations now.

The `spanish-translations` branch has a default `es.yml` file with a copy of all our english strings that need translated. As we translate, we'll want to make sure that structural aspects like translation lengths are approximately similar (and massage the string until they are) to account for the design (e.g. we intentionally have each of content cards on the landing page around the same length).

You can view `app/views/main/index.html.erb` to see how the landing page strings (scoped under `landing_page` in the YML file) are used. There are some translations around the site that aren't included in the locale files yet, but the landing page is fully-covered and should be a good starting point.

Until all translations are in place and this is ready to release, lets keep the internationalization effort on the `spanish-translations` branch and merge in one go.

**Comment by diazabdulm** [comment]
I can work on it, drusepth

**Comment by diazabdulm** [comment]
https://ufile.io/hmv6x

That's a start. I can continue translating this week or so

**Comment by cescfamadas** [comment]
Hello, if you think I can help you translate it.

If you can upload the file, I will start translating it.

**Comment by drusepth** [comment]
Due to GDPR regulations, we're holding off on all international translations. I'll reopen this issue if that changes.
