### ISSUE TITLE
Creatures description still says "plantlife", even though they have their own category

### ISSUE THREAD

**Issue by ViKomprenas** [indentlabs/notebook#249]
### Expected behavior

It doesn't.

### Actual behavior

It does.

### Steps to reproduce the behavior

Create a new universe. Filter to that universe. View the empty Creatures page.

**Comment by drusepth** [comment]
Good catch. I'll fix this tomorrow. 👍

**Comment by drusepth** [comment]
Fixed with https://github.com/indentlabs/notebook/commit/77ba740f8d347054e6628ae52cd33a4cb6a657c1
