### ISSUE TITLE
We should explain what referrals give users without needing them to refer someone first

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#251]
### Expected behavior
- Users should know what referring a user gives them

### Actual behavior
- Until they refer a user, the referral box just says "You've referred 0 users"

**Comment by smeagolthellama** [comment]
what does it do?

**Comment by drusepth** [comment]
Done & live.

![2019-04-09-194251_1168x167_scrot](https://user-images.githubusercontent.com/538235/55843797-af8e2700-5aff-11e9-94b0-f24955c68b22.png)
