### ISSUE TITLE
Postgres database needs upgraded

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#253]
[Reference](https://elements.heroku.com/addons/heroku-postgresql)

We're currently on the $9/mo Hobby Basic plan. With current load, we should probably upgrade to the $200/mo Standard 2 plan. We've got some time before we hit our limits, but if we see any other growth spurts we should probably be ready ahead of time instead of trying to upgrade a DB (with downtime) during the spike.

**Comment by drusepth** [comment]
This is done.

**Comment by mpigsley** [comment]
@drusepth Hot damn. Growing up!
