### ISSUE TITLE
Let users log in with Google, Twitter, or Facebook

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#28]
And also link their Google/Facebook/Twitter to their existing account so they can log into it that way also.

**Comment by andrewcarreiro** [comment]
Anyone taking this? My rails is rusty (pun INTENDED) but I could take a stab at it.

**Comment by Cantido** [comment]
No one has taken it yet; this will have to hook into Devise, and I don't know Devise too well. You are welcome to give it a try!

**Comment by drusepth** [comment]
@andrewcarreiro Go for it! I've used Devise+OmniAuth in the past to great success and it's what I'd recommend. Lots of OAuth providers and it should be pretty easy to set up. Has been a few years for me as well though!

**Comment by andrewcarreiro** [comment]
On it! Will bump this if I can't make headway or need some feedback

**Comment by drusepth** [comment]
The code for this is done in #231 but needs tested (and tests written) so it doesn't become a source of magic tech debt later.

**Comment by drusepth** [comment]
Since we want to provide an OAuth service in the future (to allow people to log into other sites with their Notebook.ai account), I don't think we'll end up implementing this to ensure every user can log in with their own credentials instead of relying on social accounts.
