### ISSUE TITLE
Upgrade Heroku stack

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#290]
Whenever we deploy to Heroku, we get the following message:
```
remote:  !   Warning: You are running on a deprecated stack.
remote:  !   Please upgrade to the latest stack by following the instructions on:
remote:  !   https://devcenter.heroku.com/articles/upgrading-to-the-latest-stack
```

We should probably do this soon.

**Comment by drusepth** [comment]
We've had so many Heroku issues lately, it might be worth looking at AWS instead.

**Comment by Dave-LeDev** [comment]
Appears to be affecting the main site currently.

![error message](https://i.gyazo.com/5882d5c425424d0f1596ddf216a55bdc.png)

**Comment by drusepth** [comment]
Looks like it's a problem with their server autoscaling. When a new server is provisioned, requests are routed to it before it's ready, which starts building up a long queue of requests that eventually time out. While these requests are waiting to time out, additional requests are being queued behind them, which also time out because they're waiting on the previous requests to time out. This repeats until all requests are simply waiting for all other requests, and the site goes entirely down. 

I've disabled server autoscaling until I hear back from support again, and will just bump up to the highest tier of servers until then. Which also means it'll be a good idea to swap to AWS soon, if only because the equivalent self-hosted servers are significantly cheaper. With this in mind, I'll leave this issue open and potentially still upgrade the Heroku stack (because maybe that's what's causing the autoscaling issue?) since I don't have plans to move over quickly (because I don't feel comfortable enough leaving all the Heroku guardrails and support behind quite yet), but it's definitely something to do eventually.

**Comment by drusepth** [comment]
Testing the new stack on staging seems to work just fine, so I'll upgrade production tonight and test it with autoscaling again. 

```
heroku stack:set heroku-18 -a production-1
```

**Comment by drusepth** [comment]
Production is now on the `heroku-18` stack. I'll do some autoscaling testing tomorrow.
