### ISSUE TITLE
Linking Characters To The Religions They Follow

### ISSUE THREAD

**Issue by GreyJack** [indentlabs/notebook#292]
### Expected behavior
Being able to link a Character to a Religion you have created, to signify their adherence to it. Most likely through the "Social" tab. Much like you can link them to a Race in the "Looks" tab.
### Actual behavior
The only option available is writing your Religion down into a field, without linking it.

**Comment by GreyJack** [comment]
I swear, I'm not obsessed with religions. I don't know why all the issues I've found are related to the divine.

**Comment by GreyJack** [comment]
Oh, indeed it would! 
I would say, however, that it would be nice to have a corresponding field for Religions, as well. So that if you linked Character's page to the Religion with that, they'd automatically be placed into a "Followers" (Or whatever you'd like to call it) field on the Religion's page. Like what happens with relations, for instance.
Is that Migration? That was the impression I've gotten.

**Comment by drusepth** [comment]
Yeah, that's the downside of taking this more fluid, less semantic approach to relating pages together. Those kinds of link reciprocation are still something I'll need to figure out, but my best guess at this point is that those cards will probably be (eventually) replaced with "mentions" cards. On a religion page, for example, there might be a card for "Mentioned in 'Religion'" that lists all the characters that mention that religion in their "Religion" field. 

Obviously, that's a bit rough, but that's also why these existing links are sticking around for now -- gotta figure out those reciprocations as well; I think they're super cool to have.

**Comment by GreyJack** [comment]
Agreed, I'd hate to see them go! 
I don't know if I'd think "mentions" cards would be quite as interesting. But, I don't think they'd be too missed if you're able to get that "Family tree" feature, mentioned in a much older issue, implemented. It would give us something even better to use, instead.
