### ISSUE TITLE
Missing info from Instructions

### ISSUE THREAD

**Issue by dracodragon777** [indentlabs/notebook#298]
### Expected behavior
Clear installation instructions.
### Actual behavior
Going to many git repositories not knowing what to install.
How does one install rbenv to do the command "rbenv install 2.5.1"?
Where do I get the command bundle and rake to run it?
### Steps to reproduce the behavior
Reading the instructions.

**Comment by drusepth** [comment]
README has been clarified. `rbenv` is one of the popular Ruby version managers, and that's just installing Ruby 2.5.1. As long as you have Ruby installed you should be good on that front.
