### ISSUE TITLE
Removing Premium users who haven't paid

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#301]
Right now, there's users who are on Premium without active payments (often because their existing card expired and they weren't automatically removed).

We should:

1. Get a list of email addresses of all users with `unpaid` subscriptions in Stripe (and have been retried enough that Stripe gave up on retrying)
2. Remove those users' invalid payment methods from Stripe (this'll allow them to add a card without having to remove their existing one)
3. Remove those users' current subscription from Stripe
4. Remove those users from Premium on Notebook.ai (this'll allow them to upgrade again without downgrading-then-upgrading)
5. (Optional) Send them an email saying they were removed from Premium, since they didn't get an email when their last payment(s) failed and being suddenly removed might be confusing

**Comment by amymartika** [comment]
@drusepth Most users who are 60+ days past due don't have a payment method on their account. You may want to set up an alert when they remove their payment method reminding them that their subscription will be canceled if a new method isn't added by [date].

**Comment by amymartika** [comment]
@drusepth Stripe now automatically sets user status to "canceled" for those who have failed payment methods. We need this to communicate with the site so that their Notebook subscription status matches their Stripe status.

**Comment by amymartika** [comment]
@drusepth Spreadsheet of past due users: https://docs.google.com/spreadsheets/d/1MZZ-PHIKVxN2IQlpZ0ENTGkk0_JNwQuqy1gROpxg2s8/edit?usp=sharing

**Comment by drusepth** [comment]
@amymartika I've used this email template in the past when removing someone, to explain what happened. Feel free to use, modify, or completely scratch. :)

https://docs.google.com/document/d/11jjS-o_8vX6XcXElHeZN_fjiRjlh3VfL05pJ3jtJlsw/edit?usp=sharing

**Comment by amymartika** [comment]
Email: https://docs.google.com/document/d/1LS9ri1ynnQdnKFRaynL5tGC-l0uTGmWOuDo3KdEQ7JY/edit?usp=sharing

**Comment by amymartika** [comment]
All billing is up to date. For now, I'll manually check overdue status on a weekly basis until we automate it.
