### ISSUE TITLE
`notebook.ai` does not redirect to `www.notebook.ai`

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#33]
Just try it:
 - http://notebook.ai
 - http://www.notebook.ai

**Comment by Cantido** [comment]
Assigning to @drusepth because I'm assuming you're able to update domain info on notebook.ai.

**Comment by drusepth** [comment]
Yeaaaaah, this is something I need to figure out at the DNS level, which I'm not too familiar with. I'll see if I can knock this issue out tonight -- it's a pretty important one before people start using the site.

**Comment by Cantido** [comment]
Also we gotta make sure to add a `rel="canonical"` link for whichever one we decide is canon.

**Comment by drusepth** [comment]
This is finally live! We should probably make an issue for the `rel="canonical"` links. I'm not sure which should be canonical, I'd think minus the www?

**Comment by Cantido** [comment]
Yeah I'd say so, that's the trendier thing to do I guess.
