### ISSUE TITLE
Footer link to GitHub repo references old repo name

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#34]
In [`app/views/layouts/_footer.html.erb`, line 22](https://github.com/indentlabs/notebook/blob/bc6918f70a1bbd3f66c2bc85bff995f88994f748/app/views/layouts/_footer.html.erb#L22), the "Source Code" link still points to `indentlabs/Indent`. GitHub redirects that link to `indentlabs/notebook`, so the fix is not urgent.

**Comment by drusepth** [comment]
Aw, was going to quickly fix it through GitHub without context switching into notebook code, but it looks like I can't with the new protected master branch setup. Will also fix tonight... if you haven't fixed it by then. ;)

 
![2016-09-07-124642_718x265_scrot](https://cloud.githubusercontent.com/assets/538235/18322639/3eac99d4-74f9-11e6-861a-b2a83d4b465d.png)
