### ISSUE TITLE
Payment system

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#35]
Notebook needs a way to take payments, probably using Stripe? I'm not terribly familiar with setting this up, but it'll be needed for user accounts eventually.

**Comment by Cantido** [comment]
Stripe sounds like the most ideal solution, it's made exactly for small businesses. What are our other options? PayPal might be another option.

**Comment by LarrySawyer** [comment]
I recommend Stripe. With PayPal, if you want a seamless payment process (user stays on the site vs. jumping to PayPal and back), you need PayPal Payments Pro, which is $30/month. Stripe does the same without the monthly fee. Both Stripe and PayPal take a 2.9% + $0.30 fee per transaction. (So for each $20 payment, you would keep $19.12.) Plus, I just think Stripe is a better experience overall.

**Comment by mpigsley** [comment]
I'll throw my vote in here with Stripe as well. Had great service and reliability with them and it's easy to integrate as well.

**Comment by drusepth** [comment]
FYI this is coming along nicely (in #174) and should go out sometime this week.

**Comment by drusepth** [comment]
This is live! (Using Stripe)
