### ISSUE TITLE
Linking on Self-Hosted Instance

### ISSUE THREAD

**Issue by thetrumper** [indentlabs/notebook#352]
Not entirely sure that this is a bug because I don't know if notebook was meant to be hosted on a home server but that's what I currently am doing for sake of having my own data and being able to edit when offline. The issue is when linking content, clicking on that link automatically redirects to notebook.ai instead of the server that it is installed on.

That is, an item at http://192.168.1.112:3000/plan/items/1 can be linked on say a character's page but following that link will try to go to http://www.notebook.ai/plan/items/1

Is there any configuration to change this? Is it a bug?

**Comment by thetrumper** [comment]
Not really a developer but I think it might be this: https://github.com/indentlabs/notebook/blob/34be97c3455dbb45d8c55ea428fd02b74c7937aa/app/services/content_formatter_service.rb#L98-L110

**Comment by drusepth** [comment]
Ah, thanks for this. Not too many people run notebook locally, so it's nice to get issues like this. :) 

To fix it, did you change the `'www.notebook.ai',` line to `Rails.application.routes.default_url_options[:host]` or did you just hard-code localhost? Happy to accept a pull request on the issue if you'd like to submit one!

**Comment by thetrumper** [comment]
I just changed 'www.notebook.ai' to '192.168.1.112:3000'

I'm not really a developer and don't really know Rails and thus can't really submit a pull request but my goal is to go into the computer science field and hopefully learn to make amazing things like your program :)

**Comment by drusepth** [comment]
Ha, well.. well done, then! :) 

That'll work for you as long as your computer's internal IP (on your network) remains 192.168.1.112. There's nothing wrong with that, but you might also try replacing that IP with `localhost`, which is a handle little shortcut for "whatever computer this is". So, for example, `localhost:3000` should resolve to 192.168.112 right now, but if your IP changes to something like 192.168.1.113 later, it'll resolve to 192.168.1.113 then without you needing to keep updating the config IP to whatever your machine happens to be. 

I'll include a change in an upcoming PR that changes this to use `localhost` when notebook is run in development mode (i.e. locally), so you can `git pull` later to get that change too if you don't want to make it yourself. :+1: 

Good luck!

**Comment by thetrumper** [comment]
Thank you! I'm using 192.168.1.112 though because I have it running on a separate old desktop machine w/ a static that I've turned into my own personal experimental server to run services like this and dip my toes in the water before venturing into computer science.

It's been very helpful and educational to learn as I've set this and other services up
