### ISSUE TITLE
Replace the link bar with @-mentions

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#355]
Right now we have a pretty janky implementation of a link bar for content pages that we're about to just copy/paste over to the document editor with #346. It's probably be significantly better to scrap what we have and replace it with a more fluid @-mention system (a la @Bob or @SomeBuilding to link pages while typing without needing the mouse).

**Comment by thetrumper** [comment]
Should this be closed with #356 ?

**Comment by drusepth** [comment]
Oh yes, good call 👍 I can definitely do better keeping issues groomed.
