### ISSUE TITLE
Goofy grammar in Serendipitous cards

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#48]
This is partly the gem's fault, but we can make it a little better in the app's localization. We can at least define an `activerecord` block in the `en.yml` file to give human names to fields like `identmarks`.

The pluralization thing is probably the gem's responsibility.

![image](https://cloud.githubusercontent.com/assets/1505603/18802553/194a0a1a-81af-11e6-93a5-1e903868db16.png)

**Comment by drusepth** [comment]
We should probably also define some kind of word lookup/translation service that maps internal things like "identmarks" to "identifying marks".

**Comment by Cantido** [comment]
right, that would happen in the localization. We can basically define `en.activerecord.character.identmarks: identifying marks`

**Comment by drusepth** [comment]
Oh, nice! Forgot that was a possibility. Is there anything along those lines we could do to define the verb is/are, or question word What/Where/Who/etc for each?

**Comment by Cantido** [comment]
Not as far as I know, but I know that the localization stuff is pretty powerful, so I'm sure there's a gem for that. At the very least, that sounds like the perfect thing for Serendipitous to allow in configuration.
