### ISSUE TITLE
Users should be able to upload images to content

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#52]
We should implement image uploads with S3 as a concern we can include on any content type, so users can upload as many images as they'd like to any content they own.

In terms of filesize limits, lets start out by not limiting individual images, but giving each user up to 30MB of usable upload space they can spend uploading images to any content.

After uploading an image, users should be able to browse thumbnails of all images uploaded to their content (from a gallery tab on that content), as well as
- [ ] expand images to a full-screen view
- [ ] delete images from S3 (and free up user upload space)

**Comment by Cantido** [comment]
I had an idea about this: Universes could have a cover image or background image, and any content in that universe would have that cover image behind their main image on their own show pages. When we implement #26, I am imagining horizontal, rectangular cards for each universe, and there's thin bar of their cover image on each card.

**Comment by drusepth** [comment]
That's a great idea. I'd love to redesign the content list pages as well using cards for each character/etc instead of just boring lists. Having images on each (and a default image otherwise) would make that redesign a lot easier.

Also, for this issue, we should probably separate images uploaded to content into public and private images (and ideally offer a way to move images between the two without deleting/reuploading). I imagine some people might want to share their concept art and such with their content, but I could also see reasons they'd want to store images privately also (inspiration, images they don't have copyright for, etc). Might add enough complexity to be its own follow-up feature, but definitely something to keep in mind.

**Comment by mpigsley** [comment]
Would love to see this feature! For locations especially I'd like to upload maps.

**Comment by drusepth** [comment]
Here's the proposed gameplan for this; suggestions welcome:

Setup:
1. Migrate an `upload_bandwidth` property onto all users (indicating the amount of space allowed for them to upload), defaulted to 30MB. 

Backend:
* Model changes developed as an `allows_file_uploads` concern we can include on any Content subclass.
* Controller changes (image: create, update, show, delete) added to ContentController.
* On upload, images will be processed for size and proxied through to S3 if the size is within the user's `upload_bandwidth` (and subtracted). 
* By default, images on content will be `public` and can be toggled `private`. Content still has to be `public` to even get to the images upon sharing, though.

Frontend:
* Each content type will now have a "Gallery" tab. 
* On content#show, that gallery tab will just have thumbnails of uploaded images.
* Clicking on images will expand them in a lightbox.
* On content#edit, the gallery tab will have links under each image to rename, delete, change privacy, or "make cover".
* If a piece of content has a "cover" image, it's displayed at the top of content#show (similar to the banners at the top of content#list pages), and clicking on it will expand into a full-size lightbox.

Space upgrades:
* Obviously, 30MB isn't going to last forever, but we can tackle space upgrades as a separate feature after this one.

**Comment by drusepth** [comment]
This is done and live. :+1:
