### ISSUE TITLE
Disable Registration?

### ISSUE THREAD

**Issue by tbirrell** [indentlabs/notebook#537]
Is there a way to disable registration on a self hosted application to lock it down to my guild and prevent random individuals or bots from creating accounts on my server?

**Comment by drusepth** [comment]
I haven't done it, but you should be able to remove the `:registerable` parameter to `devise` in the User model. [Devise](https://github.com/plataformatec/devise) is a plugin that handles all of the user registration, sign-in, sessions, etc, and I believe that should disable registration of new accounts.

**Comment by tbirrell** [comment]
It didn't work. But the holidays happened and I haven't had time to figure out why.

**Comment by drusepth** [comment]
You'll want to make sure you restart the server after the change, but [here's a few other strategies you can use to disable registration](https://stackoverflow.com/questions/39773890/how-to-remove-disable-sign-up-from-devise) with Devise.
