### ISSUE TITLE
Each piece of content should have an edit history

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#57]
Whenever anything changes on a piece of content, we should create some kind of EditedContentEvent that tracks what changes were made, by whom, and when. That way, we can also have an "edit history" page for content that lets users see who made changes (especially when universes can have multiple collaborators, #25), and be able to revert undesirable/mistaken changes more easily.

**Comment by heydonovan** [comment]
Have you checked out the `paper_trail` or `audited` gem?

**Comment by drusepth** [comment]
Implementation:

- Whenever a Universe, Character, Location, Item, Creature, Race, Religion, Group, Magic, Language, or Scene is created or edited, a `ContentChangeEvent` should be created with the following properties:
  - `user_id` - ID of the user making the change
  - `changed_fields` - hash of field changes (e.g. old and new values), probably best to grab from `dirty_fields` during the save hook
  - `created_at` - automatically set, self explanatory
  - `content_id` - the ID of the associated content, e.g. 5 or 8185
  - `content_type` - the content type, e.g. :character, :location, :race, etc

When visiting a content's page in the notebook, there should be an additional pane tab for "Changelog" (similar to the Gallery setup, which needs refactored eventually with a new design). Opening this pane should show a timeline consisting of:

- The date/time this piece of content was created, and by which user (`user_id` on the content itself)
- Any `ContentChangeEvent`s associated with this content with a diff view of which fields changed and what their old and new values were (probably need some cleanup here later, but lets just show it all for now)

Whenever a non-Universe piece of content is deleted, we should create a `ContentChangeEvent` for its universe (if any) that says that content and content type was deleted (e.g. "Character Bob was deleted by Alice") for display on the universe's Changelog pane.

**Comment by drusepth** [comment]
This is done and live. Improvements should have separate issues. :+1:
