### ISSUE TITLE
No SEO

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#6]
I tweeted a link to Notebook, and look at this!

![image](https://cloud.githubusercontent.com/assets/1505603/18237061/981dfa16-72f2-11e6-8a7b-4137ff1a1002.png)

There's no image, no description, anything. We need to add some twitter meta information, and probably some other info while we're in there.

Here's a gem that looks handy: https://github.com/kpumuk/meta-tags

Some really handy data can be found here: https://moz.com/blog/meta-data-templates-123

**Comment by drusepth** [comment]
Not a lot of info on G+, either.

![2016-09-04-230541_550x741_scrot](https://cloud.githubusercontent.com/assets/538235/18237200/329d8614-72f4-11e6-829f-c3e4441c09fa.png)
