### ISSUE TITLE
docker-compose up fails due to migration issue

### ISSUE THREAD

**Issue by joelmichael** [indentlabs/notebook#610]
### Expected behavior
`docker-compose up` runs successfully.

### Actual behavior
```
web_1  | == 20200103185508 AddContributableContentIndexes: migrating ===================
web_1  | -- add_index(:characters, [:user_id, :universe_id, :deleted_at])
web_1  |    -> 0.0224s
web_1  | -- add_index(:locations, [:user_id, :universe_id, :deleted_at])
web_1  |    -> 0.0033s
web_1  | -- add_index(:items, [:user_id, :universe_id, :deleted_at])
web_1  |    -> 0.0029s
web_1  | -- add_index(:buildings, [:user_id, :universe_id, :deleted_at])
web_1  |    -> 0.0019s
web_1  | -- add_index(:conditions, [:user_id, :universe_id, :deleted_at])
web_1  |    -> 0.0017s
web_1  | -- add_index(:continents, [:user_id, :universe_id, :deleted_at])
notebook_web_1 exited with code 1
```

### Steps to reproduce the behavior
Run `docker-compose up` on a fresh install.

Recommend possibly switching to `db:setup` instead of `db:migrate` for initial installation. These migration files are probably failing due to alterations in the context since they were created. Seems the continents table does not exist at the time this migration is run.

**Comment by drusepth** [comment]
Ah, yep. That's a big oof on my part. I used `Rails.application.config.content_types[:all_non_universe]` in the migration so I wouldn't have to type each content type out by hand, but obviously it's changed since then as more content types were added. 

I'll take a look at switching to `db:setup` today and get this sorted out.

**Comment by joelmichael** [comment]
@drusepth I made a PR for it earlier if you want to check it out.

**Comment by drusepth** [comment]
Merged. :+1:
