### ISSUE TITLE
Running rake db:migrate results in SQLite3::SQLException

### ISSUE THREAD

**Issue by WilliamSBunin** [indentlabs/notebook#649]
### Expected behavior
Running `rake db:migrate` should work

### Actual behavior
It gives errors..

### Steps to reproduce the behavior
I ran `rake db:migrate` (following the directions to install) and received the following error

````
RAILS_GROUPS is unset; defaulting to web,worker
== 20200103185508 AddContributableContentIndexes: migrating ===================
-- add_index(:characters, [:user_id, :universe_id, :deleted_at])
   -> 0.0046s
-- add_index(:locations, [:user_id, :universe_id, :deleted_at])
   -> 0.0026s
-- add_index(:items, [:user_id, :universe_id, :deleted_at])
   -> 0.0061s
-- add_index(:buildings, [:user_id, :universe_id, :deleted_at])
   -> 0.0025s
-- add_index(:conditions, [:user_id, :universe_id, :deleted_at])
   -> 0.0025s
-- add_index(:continents, [:user_id, :universe_id, :deleted_at])
rake aborted!
StandardError: An error has occurred, this and all later migrations canceled:

SQLite3::SQLException: no such table: main.continents
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:4:in `block in change'
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:3:in `each'
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:3:in `change'

Caused by:
ActiveRecord::StatementInvalid: SQLite3::SQLException: no such table: main.continents
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:4:in `block in change'
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:3:in `each'
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:3:in `change'

Caused by:
SQLite3::SQLException: no such table: main.continents
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:4:in `block in change'
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:3:in `each'
.../notebook/db/migrate/20200103185508_add_contributable_content_indexes.rb:3:in `change'
Tasks: TOP => db:migrate
(See full trace by running task with --trace)
````

I'm running windows, but using Ubuntu terminal. I've had many issues trying to set up a local setup, but have finally made it this far. What am I missing?

**Comment by drusepth** [comment]
Hey William, it looks like this happens because we iterate over `Rails.application.config.content_types[:all_non_universe]` in the migration that's failing. That's a config setting that holds all of our content types but has changed since that migration was originally written, and now it looks like it's trying to modify some of these page types before future migrations add their table.

You should be able to fix this by running `rake db:schema:load` instead of `rake db:migrate` to load the `db/schema` file directly without error (and skipping all the individual migrations). If this works for you, would you mind submitting a PR to changing the build instructions, or let me know so I can change them? :)

**Comment by WilliamSBunin** [comment]
Ran `rake db:schema:load`

````
RAILS_GROUPS is unset; defaulting to web,worker
rake aborted!
ActiveRecord::NoEnvironmentInSchemaError:

Environment data not found in the schema. To resolve this issue, run:

        rails db:environment:set RAILS_ENV=development


Tasks: TOP => db:schema:load => db:check_protected_environments
(See full trace by running task with --trace)
````

So I ran `rails db:environment:set RAILS_ENV=development` which succeeded then `rake db:schema:load` which succeeded.

No idea how to make a PR or submit one.

**Comment by drusepth** [comment]
Awesome, glad it worked; thanks for the update. Don't worry about a PR, I'll get the README updated so people don't run into this issue in the future.
