### ISSUE TITLE
Site needs a favicon

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#68]

**Comment by Cantido** [comment]
I think the blue notebook icon would be great. Since the resolution is so low, maybe the icon could just be the white pen against a blue background.

**Comment by drusepth** [comment]
Do favicons still have to be .icos? Or is that a 90s thing? Uploading the book just in case (or so I can refer back to it from mspaint when I boot to windows) :P

![2016-09-26-002643_192x180_scrot](https://cloud.githubusercontent.com/assets/538235/19009016/29cc6cd6-8770-11e6-973a-9819fae45fcf.png)

**Comment by Cantido** [comment]
There are like like a million different formats what we need to provide an icon in, these days. Some frameworks generate them all from a few source images. I'll do some research. I'm sure Rails has something useful.

**Comment by drusepth** [comment]
@Cantido is the man
