### ISSUE TITLE
Small manifest.json request

### ISSUE THREAD

**Issue by s1-en** [indentlabs/notebook#681]
In the `manifest.json` file of the site, the `theme_color` is set to value `#ffffff`. As a result, when I install Notebook.ai as a PWA, I get a white titlebar which kinda clashes with its blue header.

![image](https://user-images.githubusercontent.com/63731521/81066302-7943f680-8f0f-11ea-9573-647c2699071a.png)

My request is to change this value to `#2196f3` so that it matches with the header color

**Comment by drusepth** [comment]
This makes sense to me! I'll get it changed soon, but feel free to open a PR with the change if you'd prefer. :)
