### ISSUE TITLE
Plan Worlds/Planets

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#74]
Lets get some discussion going on the best way to do this. Gotta show sci-fi bros some love.

Feedback: 

>Hello, would you please at a "planet" section? This would allow users to separate locations, (cities, oceans, etc.) from planets in the menu. It would save us a lot of time, confusion, and help with organization.

**Comment by Cantido** [comment]
Our first and most important choice is how hard-coded this should be. We could possibly add some cool functionality if we can semantically know what areas are bigger than other areas.

Or, locations could just generally be composable. Like, any location can contain any other location. We'd just have to be sure to make the graph non-cyclic.

**Comment by drusepth** [comment]
Yeah, good point. I liked your idea of having some kind of `type` dropdown that specifies scale (e.g. World, Country, ...state, city? not sure how to break all that down, or if that should be customizable too). I think the important things for AI's sake is to preserve relative size (knowing some locations "contain" other locations), and scale (knowing that a country has very different things to plan than a town or lake).

**Comment by Cantido** [comment]
Maybe `scale`? That doesn't lock content into a "type" but still helps us get a hierarchy going

**Comment by drusepth** [comment]
One planet hierarchy example from a user:
```
deep space locations (not associated with a star)
Star systems
 ->planets
    -> surface locations
    -> orbit structures
```

**Comment by Faustyna** [comment]
Being able to sort by World/Planet/Realm like you currently do Universe would be nice too.

**Comment by Faustyna** [comment]
Any idea about when this will be implemented? I have a lots of realms in my world, each with separate magics and things. Should I wait until this is done, or just make each realm its own Universe, you think?

**Comment by drusepth** [comment]
@Faustyna There's a lot of content types being requested right now that we'd like to add (namely Worlds, Groups, Events, and a few others), so I think we want to tackle being able to turn on/off content types per universe before any of them so people can pick and choose which content is relevant to their stories, so I would guess at least a week before this gets started on.

Universes aren't the best fix until then (sorry!), but they might be your best bet for doing something similar until Worlds are in place. Sorry if that's an inconvenience, we're trying to make awesome things for everyone as fast as we can!

**Comment by Faustyna** [comment]
It's totally fine! Thank you so much for all your hard work and what you're doing with this program- I love it :) I was just curious and a little impatient to use this great tool <3

**Comment by drusepth** [comment]
Starting a general outline of the fields we should expect here... Probably needs quite a bit of polishing/adding/removing before finalized.

```
Overview
  Name
  Description
  Solar system: link to Location (?)
  Universe
Looks
  Physical description
  Geography
  Weather
  Size
Culture
  Races (link to Races)
  Technologies (overlaps with universe technologies?)
Resources
  Imports (link to Items?)
  Exports (link to Items?)
```

Should also add the following links to existing content types (when Worlds are enabled for that universe):

- Character: Homeworld
- Location: World
- Item: Origin world

**Comment by andrewcarreiro** [comment]
If one starts creating different data types for classes of locations, we may make things less flexible in the future. We should probably just allow Locations to define parent-child relationships, because arguably location could have a complexity level of:

- Plane of Existence / Dimension
- Galaxy
- Cluster
- Solar System
- Planet
- Continent
- Country
- Region
- City / Town / Village / Municipality / Zone
- Building
- Floor

It may be better to create location types that would map to pre-defined property sets?
IE: Location types "Planet", "Continent", and "Region" will suggest adding climate

**Comment by drusepth** [comment]
Done & live.
