### ISSUE TITLE
Data exporter

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#76]
We can pretty easily export content in JSON/XML, but I'm not sure how useful that'd be. We should look into popular formats (Scrivener, others?) and more user-friendly formats (some outline format would be nice) and figure out at least one format to let users export their content to, both for their peace of mind and for opening up integrations with other software.

**Comment by Cantido** [comment]
We could really easily generate a PDF using Asciidoctor, too. That has a ruby API.

**Comment by Cantido** [comment]
Basically anything that has a ruby API we could write a converter for, I don't think that would be any issue at all. I think the most work would go into structuring the output in a useful & interesting way.

**Comment by drusepth** [comment]
Oooooooh, I _really_ like the idea of a PDF. We could generate a table of contents, make it look gorgeous (after our MVP to just get data to users), and make it a legit feature. I'm thinking similar to those D&D books you can buy, where it's just a big, gorgeous tome of info about people, creatures, places, and items.

**Comment by Cantido** [comment]
I'm really excited for this now. Also, I'm thinking some kind of nested navigator that lets you check/uncheck categories for export would be appreciated.

**Comment by drusepth** [comment]
e.g. 
![pathfinderpage1](https://cloud.githubusercontent.com/assets/538235/19017584/12351eb8-883f-11e6-8c1b-4c92c30908e6.jpg)

**Comment by Cantido** [comment]
Yeah I see what you mean. We can definitely do this. Also just exporting the generated Asciidoc text would let users supply their own CSS, so they can take it and polish it up however they want.

**Comment by drusepth** [comment]
Yeah, for sure. We should check everything by default in a list of 

- [x] Universes
- [x] Characters
- [x] Locations
- [x] Items

and let them select/deselect content types, but also expand each (accordion-style) and check/uncheck specific pieces of content to export also.

**Comment by drusepth** [comment]
So I think our initial data export formats should be 

* JSON blob of all universes, characters, locations, and items (replacing relation IDs with relation names)
* Human-readable outline format using a hierarchy going down from universes, e.g.

```
Universes
  Tudor Universe
    Characters
      Mr. Tudor
        Age: 85
        ...
      Mrs. Tudor
        Age: 82
        ...
      ... (other characters)
    Locations
      ...
    Items
      ...
  Second Universe
    ... (same)

  Other Universes (for content without a universe)
    ... (same)
```

Once we have those two knocked out, we can start planning an awesome PDF export to blow users away with.

**Comment by Cantido** [comment]
Another suggested format: [org-mode](http://orgmode.org/guide/)

**Comment by drusepth** [comment]
The exporter has been done & live for some time now. Lets leave future improvements to their own issues (e.g. #219).
