### ISSUE TITLE
Characters should have archetype selection

### ISSUE THREAD

**Issue by drusepth** [indentlabs/notebook#8]
1. Add "archetype" field to Characters
2. Allow users to select a value from a list populated from http://tvtropes.org/pmwiki/pmwiki.php/Main/ArchetypalCharacter

**Comment by drusepth** [comment]
We should probably add the archetypes to our `en.yml` translations file, and then do something like `<%= f.select_field t('archetypes') %>` to pull them in when rendering the partial for the archetypes field. :)

**Comment by ashleysullins** [comment]
This is live!
