### ISSUE TITLE
Internationalize the site

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#89]
We'll need to extract all strings into locale files. Fairly straightforward. For any pages that are mainly text, like the privacy policy, we can have localized ERB files instead, i.e. `privacy.en.html.erb`. I did that for [my privacy policy on Toaster](https://github.com/Cantido/toaster/blob/master/app/views/static/privacy.en.html.erb), and it's a lot more convenient than locale files.

**Comment by drusepth** [comment]
Unfortunately, we've gotta hold on this until we've spoken to a GDPR compliance officer.
