### ISSUE TITLE
Translate the site

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#90]
Depends on #89.

There are services and ruby gems that just push an `em.yml` file through Google Translate into whatever language we want. That's probably most feasible for us, but I'd at least want someone to proofread everything before we push it.

As for language choice, I think we ought to take a look at Google Analytics.

**Comment by drusepth** [comment]
Due to GDPR, we're holding off on doing any translations for now. I'll reopen this issue if that changes.
