### ISSUE TITLE
Expand on Item Types

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#91]
Feedback from a user:

>  I think this is a good tool for worldbuilding with a lot of potential It would be good if you added some kind of technology tab. The item tab is to my understanding for specific items and if you for example want to describe how a FTL-engine works and later want to describe a specific FTL-engine it could become confusing.

If we could create an "Item Type" model, then people could write up cool explanations on how their FTL-engines and stuff works, and then they could link to that from an Item to describe a specific individual FTL-engine. This could also allow for brands, makers, and other specifications.

**Comment by Cantido** [comment]
More feedback:

> It would be nice to have a separate technology page. The field for technology under the rules tab in the universe page is nice for describing the overall technological level of a world. If there's several technological concepts you want to describe however then that field becomes messy.

**Comment by drusepth** [comment]
This is done & live with #205
