### ISSUE TITLE
Custom fields

### ISSUE THREAD

**Issue by Cantido** [indentlabs/notebook#92]
Custom fields seems to be a popular request. Also, it would help us avoid adding way too many hard-coded fields that would never get used.

Having templates is a natural extension of this, and I think we could eventually extract our hard-coded fields into templates themselves.

**Comment by Cantido** [comment]
Templates would also allow for DnD character sheet templates, or whatever. Maybe we could even allow people to share templates :smirk_cat:

**Comment by drusepth** [comment]
Custom fields are live! I'm sure we'll have some features/bugs with it (as we already do), so lets go ahead and make issues specific to individual things to fix/add and close this one. Woop woop :+1:
