### ISSUE TITLE
Changing document universe does not work

### ISSUE THREAD

**Issue by ironjan** [indentlabs/notebook#925]
### Steps to reproduce the behavior

1. Open a document in edit mode
2. Click "About"
3. Click "Set in *no universe set*"
4. Select a new universe for the document
5. Close the dialog. The dialog states that changes are saved automatically.
6. Click "About" again. See "Set in *no universe set*"

### Expected behavior

The selected universe should be saved.

### Actual behavior

I observed the network traffic and found that the dialog does not trigger any network requests. Neither when changing the selection, nor when using the close button.

**Comment by drusepth** [comment]
Ah, interesting. I actually had someone else complain about this yesterday and wasn't able to reproduce it in development mode, but it looks like jQuery isn't loading in in the prod environment. I'll look into why -- I'm guessing that JS error is what's preventing all these JS events from triggering. Thanks for reporting!

**Comment by ironjan** [comment]
Thanks @drusepth , it's working now ;)
