### ISSUE TITLE
Docker installation fails

### ISSUE THREAD

**Issue by MateoPeri** [indentlabs/notebook#961]
### Expected behavior
Get to a landing page or otherwise working state.

### Actual behavior
When trying to load Notebook at \<ip\>:3000, I am presented with an error page titled `Webpacker::Manifest::MissingEntryError in Main#index`:
```
 Showing /home/notebookai/app/views/layouts/_common_head.html.erb where line #12 raised:

Webpacker can't find application.js in /home/notebookai/public/packs/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
   unless you are using the `webpack -w` or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
```

It also provides a preview of the file (`_common_head.html.erb`):
```rb
<%= render 'layouts/favicon' %>
<%= javascript_include_tag 'application' %>
<%= javascript_pack_tag 'application' %>  // THIS LINE IS HIGHLIGHTED IN RED (line 12)
<%= render 'layouts/seo' %>

<%# todo: Is there a way to play nicer with thredded's jquery? %>
```

### Steps to reproduce the behavior
Follow docker installation instructions. I did not change any file/config (is that required?):
* Clone repo.
* `docker-compose up`
* Go to \<ip\>:3000 and wait ~20 seconds for it to present the error message.

I have checked the `docker logs` for the container, but it's a mirror of what the web page is showing.
I am on Synology ds218+, docker-compose version 1.29.2 (latest). `docker-compose` file was not modified.
I can provide full traces/info dumps if needed.

**Comment by MateoPeri** [comment]
Tried the same setup on a Ubuntu 20.04 machine, same result.

**Comment by MateoPeri** [comment]
Tried to modify the Dockerfile so that it contains the same instructions as the other install method, same result.

```Dockerfile
# HEADS UP!
# This Dockerfile is for DEVELOPMENT use only;
# it's in no way optimized for production.

# The image to build from.
FROM ruby:2.7.2

# Properties/labels for the image.
LABEL maintainer="Notebook.ai Contributors"

# Copy the current folder into the notebookai user's home directory.
COPY . /home/notebookai

# Set the notebookai user's home directory as the working directory.
WORKDIR /home/notebookai

# Prep the image for runtime, this should all be done in one command
# to minimize image layers.
# See: https://docs.docker.com/develop/develop-images/dockerfile_best-practices/#minimize-the-number-of-layers
RUN groupadd --system --gid 1000 notebookai && \
    useradd --system --home-dir /home/notebookai --gid notebookai --uid 1000 --shell /bin/bash notebookai && \
    apt-get update -qq && \
    apt-get install -y build-essential libpq-dev nodejs imagemagick libmagickwand-dev && \
    rm --recursive --force /var/lib/apt/lists/* && \
    bundle install && \
    rake db:create && \
    rake db:migrate && \
    rake billing_plans:initialize_defaults && \
    rake data_migrations:create_default_billing_plans && \
    rake db:seed

# This image should expose the port 3000.
# This does not actually expose the port, you'll have to expose it yourself by
# using `-p 3000:3000/tcp` in Docker's CLI or `- "3000:3000"` in the in docker-compose.yml service's ports[].
# https://docs.docker.com/engine/reference/builder/#expose
EXPOSE 3000/tcp
CMD ["bundle", "exec", "rails", "server"]
```

**Comment by MateoPeri** [comment]
Running a fresh install using the non-docker approach on Ubuntu 20.04 provides the same error...
Are there up to date instructions on how to self host?

**Comment by drusepth** [comment]
Hey @MateoPeri, I haven't set up a new install lately but it looks like the server's running and webpack's having issues. If you're running with a production `RAILS_ENV`, you'll want to make sure you're compiling the JS manually (I believe `rake assets:precompile` should do it). If you're running in development mode and/or not compiling assets manually, you'll want to also make sure you're running `bin/webpack-dev-server`.

I'll get a notice up in the Dockerfile saying it's community-driven and might be out of date (I don't use Docker, PR's welcome!) to better set expectations for it, and also add something to the readme about running webpack for assets.

Would you let me know if running `bin/webpack-dev-server` alongside `rails server` solves the issue for you? Thanks!

**Comment by MateoPeri** [comment]
Hi, thanks for your response!
Running `bin/webpack-dev-server` from the `notebook` directory results in 
```
Traceback (most recent call last):
	6: from bin/webpack-dev-server:16:in `<main>'
	5: from bin/webpack-dev-server:16:in `chdir'
	4: from bin/webpack-dev-server:17:in `block in <main>'
	3: from /home/szeth/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/webpacker-5.2.1/lib/webpacker/runner.rb:6:in `run'
	2: from /home/szeth/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/webpacker-5.2.1/lib/webpacker/runner.rb:6:in `new'
	1: from /home/szeth/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/webpacker-5.2.1/lib/webpacker/runner.rb:13:in `initialize'
/home/szeth/.rbenv/versions/2.7.2/lib/ruby/gems/2.7.0/gems/webpacker-5.2.1/lib/webpacker/runner.rb:13:in ``': No such file or directory - yarn (Errno::ENOENT)
```

so I guess I'm missing a file. But I've followed the instructions and the directory I'm operating on is a clone of this repo. Maybe I'm not seeing something here. I'm a complete ruby/rails noob so I don't really understand how any of this works.

**Comment by drusepth** [comment]
No worries! The file is [here](https://github.com/indentlabs/notebook/blob/master/bin/webpack-dev-server) so if you've cloned the repo you should have it (you can look in the `bin` directory to be sure). It looks like it's erroring during runtime on requiring `webpacker/dev_server_runner` though, which is an external file I assume is provided by the `webpacker` gem. 

If you've already run `bundle install`, you might also try `bundle exec ./bin/webpack-dev-server` and/or `npm install --dev` to make sure the libraries are installed correctly and being used.

**Comment by MateoPeri** [comment]
It's working now!! Thanks!
Your suggestion of running `npm install --dev` worked, and for that I needed to install `nodejs`,  `npm` (with `apt`) and `yarn` (with `npm`) . I am building a Dockerfile to reflect those changes, when I finish it I'll create a PR.

Now I was trying to replicate #531 and give myself full access. The recommended approach is to modify the db manually. How would I go about that? I am assuming that with the rake command. Would I need to manually assign a plan to each user, or could I modify the 'default' plan that would apply to new users?

Also, in order to run in a production environment, do I just set `RAILS_ENV=production` when running the project (aka `bundle exec rails server`)? Is it required at install time too? This could significantly affect docker users, as building the dockerfile takes a long time, and if the env variable needs to be set at install time you would need to rebuild if you wanted to switch between prod-dev.

Thanks in advance.

**Comment by drusepth** [comment]
Awesome! Looking forward to the PR. I don't get too many Docker-related issues but I do always feel bad when I'm not more helpful.

For #531, you'll definitely want to run the rake task mentioned there to generate the default billing plans. Afterwards, you can use [the console](https://guides.rubyonrails.org/command_line.html#bin-rails-console) to more easily modify the DB, with something like `User.all.update_all(selected_billing_plan_id: 3)`. If you are more comfortable with SQL, you could also change the column default to default to whatever your "premium" billing plan IDs are. Or, of course, you could also just short-circuit all of [the authorizers](https://github.com/indentlabs/notebook/tree/master/app/authorizers) with `return true` to open up permissions for `creatable_by?(user)` across each of them.

For production, you'll want to make sure you at least do a `RAILS_ENV=production bundle install` to make sure you get all of the production-group gems/libraries, and you'll probably also want to compile your assets manually (`rake assets:precompile` any time you make a change). You'll probably also want to be running sidekiq (`bundle exec sidekiq`) for some of the features to work properly (mostly notifications, but also things like document analyses if you have an IBM Watson API key). Once the server has everything it needs to run in production mode, you should be able to switch between dev-prod by just changing RAILS_ENV (to `production` or `development`) and restarting the server (`rails server`). I'm not sure if there's a way for Docker to do that without rebuilding, but I'd assume so!
